#!/usr/bin/env python3
"""Per-industry content for the industry landing pages.

The variable across these nine is WHICH WORKFLOWS DOMINATE, not the noun.
High-consideration categories phone BEFORE buying (sizing, fitment, quote);
low-consideration categories phone AFTER (WISMO, returns, back-in-stock). That
is what keeps nine pages from being one page, and it keeps every page consistent
with our own published argument that nobody phones before buying a t-shirt.

Rule for the questions table: if a row could be copied to another industry
unchanged, it does not belong on the page. Each row names the actual field the
answer resolves against.

`proof` renders only where it is true. No invented logos, no illustrative
customer names.
"""

INDUSTRIES = {

# ─────────────────────────────────────────────────────── HOME IMPROVEMENT
"home-improvement": {
  "label": "Home Improvement / HVAC", "when": "before", "scene": "hvac",
  "title": "Voice AI for HVAC &amp; Home Improvement E-Commerce | Sabato AI",
  "description": "A managed voice agent that sizes the unit, checks the climate zone and books the site visit - from your own kW tables and ERP. Live in two weeks.",
  "h1": "Heating and cooling buyers phone before they buy.",
  "sub": "Sabato's managed voice agent sizes the unit, checks the climate zone, says what the installation actually includes - and books the site visit while the caller is still interested.",
  "hand": "in this category the call is the configurator",
  "call_q": "&ldquo;I&rsquo;ve got 120 m&sup2; on one floor just outside Milan - is the 9 kW split the right one?&rdquo;",
  "call_meta": [("Detected intent","Sizing + installation"),("Data pulled","kW table &middot; climate zone E"),("Outcome","Site visit booked")],
  "band_eyebrow": "Why this category phones",
  "band_h2": "A heat pump is a specification decision made by someone who doesn&rsquo;t have the specification.",
  "band_copy": ["Nobody buys 12 kW. They buy a house: 120 m&sup2;, built in 1978, single floor, radiators they&rsquo;d rather keep, a postcode with a specific winter design temperature. The product page cannot answer that, so the buyer either phones or leaves.",
                "That call is not support. It is the last step of the sale, and it lands during working hours on a line that is usually already busy with an installer asking about a delivery."],
  "rank_head": "What the inbound calls are about",
  "rank": ["Which unit for my space (sizing)","Installation: included, who, when","Price, discount, quote for a full system","Incentives and certification documents","Delivery timing and where the order is"],
  "questions_h2": "Six questions an HVAC line hears every day - and what has to be true in your systems to answer them",
  "questions_intro": "An agent is only as good as what it can read. These are the pairings that matter in heating and cooling: each question resolves against a specific field, not against a general knowledge of HVAC.",
  "questions": [
    ("&ldquo;Which unit do I need for 120 m&sup2; on one floor?&rdquo;","kW/BTU sizing table crossed with the climate zone for the caller&rsquo;s postcode and the declared ceiling height.","product.heating_capacity_kw &middot; zone.design_temp"),
    ("&ldquo;Is installation included, and who does it?&rdquo;","Installer coverage by postcode plus the installation service SKU and its current lead time.","installers.by_cap &middot; sku.INSTALL_STD"),
    ("&ldquo;Will it work with the radiators I already have?&rdquo;","Maximum flow temperature on the unit against the emitter type the caller describes; hands over to a human when the answer is borderline.","product.max_flow_temp_c"),
    ("&ldquo;Does this model qualify for the incentive scheme?&rdquo;","ErP energy class and SCOP value from the certification documents held in the DAM, sent by email as the PDF itself.","docs.erp_class &middot; docs.scop"),
    ("&ldquo;If I order today, when does it arrive?&rdquo;","Available-to-promise in the ERP, plus the supplier lead time when the item is not in the warehouse.","erp.atp &middot; supplier.lead_days"),
    ("&ldquo;Where is the rest of my installation kit?&rdquo;","Carrier tracking events on the parent order, split shipments reconciled into one answer.","carrier.events &middot; order.shipments[]")],
  "workflows": [("Pre-sales consultation","Sizing, compatibility, what&rsquo;s in the box. The call that decides the sale.","/use-cases/pre-sales-consultation"),
                ("Qualify &amp; collect for quote","Full-system enquiries captured with the fields an installer quote actually needs.","/use-cases/qualify-and-collect-for-quote"),
                ("Where is my order","Split shipments and installation kits, reconciled into one spoken answer.","/use-cases/where-is-my-order"),
                ("Checkout summary via text","Confirming a four-line order with an install slot before the card is charged.","/use-cases/checkout-summary-via-text")],
  "transcript_meta": "Inbound &middot; 2 min 41 s &middot; language: Italian, translated here &middot; outcome: site check booked",
  "transcript": [("caller","Hi - I&rsquo;m looking at the 9 kW split on your site. I&rsquo;ve got about 120 square metres, all on one floor, just outside Milan. Is that the right one?"),
    ("agent","Let me check the sizing table. 120 square metres on one floor, climate zone E - for cooling you&rsquo;re at roughly eleven to twelve kilowatts, so the 9 kW would be running flat out in August. The 12 kW is the safer fit. Is the ceiling height standard, around 2.7 metres?"),
    ("caller","Yes, standard. Nothing unusual."),
    ("agent","Then the 12 kW. One thing to know before you order: it needs a dedicated sixteen-amp line. If you&rsquo;re not sure you have one, the installer checks that on the site visit."),
    ("caller","That&rsquo;s the other thing - is the installation you, or do I find someone myself?"),
    ("agent","Three certified installers cover your postcode. Installation is quoted separately after the site check, and the site check is free and takes about twenty minutes."),
    ("caller","And does it qualify for the incentive?"),
    ("agent","This one is ErP class A+++ with an SCOP of 4.6, so yes. I&rsquo;ll email you the certification PDF and the two nearest installers. Shall I book the site check now?"),
    ("caller","Yes, go ahead.")],
  "data_h2": "The data reality behind an HVAC answer",
  "data_copy": "Every answer on this page depends on a field somebody has to maintain. Where a field is missing we say so on the call and hand over - we do not let the agent reason its way to a kilowatt figure.",
  "data_rows": [("kW / BTU sizing tables","Per model, with the assumptions stated: floor area, ceiling height, insulation class."),
    ("Climate zone by postcode","Zones A - F or the local equivalent, mapped to winter design temperature."),
    ("ErP class, SCOP, SEER","As documents, not as marketing copy - the agent emails the PDF the incentive scheme asks for."),
    ("Installer coverage","Which certified installers serve which postcodes, and their current booking horizon."),
    ("ERP available-to-promise","Stock plus inbound purchase orders, so lead times spoken on the phone are the ones the ERP will honour.")],
  "proof": "Sabato answers the phone for ClimaConvenienza - heat pumps, boilers and air conditioning, on Shopify.",
  "faq": [("Can an AI voice agent really size a heat pump on the phone?","It reads your sizing table against the caller&rsquo;s floor area, ceiling height and climate zone, and it flags the cases that need a human - borderline emitter compatibility, three-phase supply, anything unmapped. It does not invent a kilowatt figure. Sizing that ends in an order should still be confirmed on the site visit, and the agent books that visit."),
    ("Does it work in Italian and English on the same line?","Yes. The agent detects the caller&rsquo;s language on the first turn and stays in it for the whole call, including the email it sends afterwards. Sabato is built for European merchants, so multilingual is the default, not an add-on."),
    ("What happens outside opening hours?","The agent answers, handles what it can from your systems - order status, availability, documents - and books a callback with the installer team for anything that needs a human. Evening and weekend calls are the ones HVAC merchants lose most often."),
    ("How does this differ from a chatbot on the product page?","Sabato answers the phone. In high-consideration categories the buyer has already decided that typing is not enough - they want to describe their house to someone. A chat widget cannot take that call, and a voicemail box loses it."),
    ("What does it need from our Shopify store to go live?","Read access to orders and products, your sizing and certification documents, and the installer coverage list. Most HVAC merchants have the first two and keep the third in a spreadsheet; that is fine, we map it.")],
  "cta_h2": "Hear the agent take an HVAC sizing call",
  "cta_sub": "We&rsquo;ll run a live call against your own catalogue on the intro call - your sizing table, your postcodes, your questions.",
  "cta_hand": "twenty minutes, no deck"},

# ─────────────────────────────────────────────────────── AUTOMOTIVE
"automotive-parts": {
  "label": "Automotive &amp; Parts", "when": "before", "scene": "auto",
  "title": "Voice AI for Automotive Parts E-Commerce | Fitment Calls | Sabato AI",
  "description": "Parts buyers phone to ask one question: does it fit my car? A managed voice agent that answers it from your fitment data, VIN lookup and supersession chains.",
  "h1": "Every parts call is the same question wearing a different car.",
  "sub": "Does it fit mine? Sabato's agent takes the registration or the VIN, checks it against your fitment table, and says yes, no, or &ldquo;that one was superseded - here&rsquo;s the current part&rdquo;.",
  "hand": "fitment is the whole conversation",
  "call_q": "&ldquo;I&rsquo;ve got a 2016 Golf, 2.0 TDI - will these front discs fit it?&rdquo;",
  "call_meta": [("Detected intent","Fitment check"),("Data pulled","VIN &middot; fitment table"),("Outcome","Confirmed + upsold pads")],
  "band_eyebrow": "Why this category phones",
  "band_h2": "A wrong part is a return, a refit and a customer who buys the next one somewhere else.",
  "band_copy": ["Parts buyers are not browsing. They have a car in pieces, or a customer waiting, and a specific question: does this fit. Get it wrong and you pay the return, the courier, and often a labour claim from a garage that already started the job.",
                "The product page can host a registration lookup, and it should. It still cannot answer &ldquo;mine&rsquo;s a facelift model, does that change the caliper?&rdquo; - which is exactly the call that arrives instead."],
  "rank_head": "What the inbound calls are about",
  "rank": ["Does this fit my vehicle (reg or VIN)","Is this the right variant - facelift, engine code, trim","Was this part superseded, what replaced it","OEM vs aftermarket, and is it equivalent","Where is my order, I have a car on a ramp"],
  "questions_h2": "Five questions a parts line hears every day - and what has to be true in your systems to answer them",
  "questions_intro": "Fitment is a data problem before it is a service problem. Every answer here resolves against a specific table, and where the table is thin the agent hands over rather than guessing - a confident wrong fitment is the most expensive answer in this category.",
  "questions": [
    ("&ldquo;Will this fit a 2016 Golf 2.0 TDI?&rdquo;","Registration or VIN decoded to the exact vehicle variant, then matched against the fitment table for the part family.","vehicle.by_vin &middot; fitment.k_type"),
    ("&ldquo;Mine&rsquo;s the facelift - does that change anything?&rdquo;","Build-date range on the fitment record, which is where most wrong-part orders actually originate.","fitment.build_from &middot; fitment.build_to"),
    ("&ldquo;That part number doesn&rsquo;t come up any more.&rdquo;","Supersession chain followed to the current part, with the original number kept in the order notes for the garage.","part.superseded_by[]"),
    ("&ldquo;Is the aftermarket one as good as the OEM?&rdquo;","Brand tier and the OE reference cross-match, stated as an equivalence claim from your data - not as an opinion the agent invents.","part.oe_refs[] &middot; brand.tier"),
    ("&ldquo;I need it tomorrow, the car&rsquo;s on the ramp.&rdquo;","Stock by warehouse plus the cut-off time for next-day dispatch on the caller&rsquo;s postcode.","stock.by_wh &middot; carrier.cutoff")],
  "workflows": [("Pre-sales consultation","The fitment call. The one that decides whether the order is right.","/use-cases/pre-sales-consultation"),
                ("Where is my order","A garage with a car on a ramp asks differently. Answered from live carrier events.","/use-cases/where-is-my-order"),
                ("Managing returns","Wrong-part returns triaged by cause, so the fitment data gets fixed rather than the return processed.","/use-cases/managing-returns"),
                ("Checkout summary via text","Part number, vehicle and fitment confirmation in writing before the card is charged.","/use-cases/checkout-summary-via-text")],
  "transcript_meta": "Inbound &middot; 1 min 58 s &middot; language: English &middot; outcome: order placed, correct variant",
  "transcript": [("caller","Hi, I&rsquo;m after front brake discs for a Golf, 2016, the 2.0 diesel."),
    ("agent","I can check that exactly if you have the registration."),
    ("caller","Yes - it&rsquo;s a Mark 7, reg is on the paperwork here, one moment."),
    ("agent","Take your time. While you find it: is it the standard model or the GTD?"),
    ("caller","Standard. Reg is BD16 ZKP."),
    ("agent","Got it - 2016 Golf 2.0 TDI, built March 2016, which puts it after the facelift. That takes the 312 millimetre vented disc, not the 288 the earlier cars use. The ones you were looking at are the 288, so those would not fit."),
    ("caller","Good job I called."),
    ("agent","The 312 pair is in stock in the Birmingham warehouse, cut-off for next day is four o&rsquo;clock. Most people take the pads at the same time - same axle, same job. Want me to put both on?"),
    ("caller","Yes, both.")],
  "data_h2": "The data reality behind a fitment answer",
  "data_copy": "Fitment data ages badly. Manufacturers revise, supersede and re-reference constantly, and a table that was correct two years ago will quietly produce wrong answers today. We audit these before the pilot.",
  "data_rows": [("Vehicle decode","Registration or VIN to the exact variant: engine code, build date, trim."),
    ("Fitment table","Part family to vehicle variant, with build-date ranges - the field most often missing."),
    ("Supersession chains","Old part number to current, so a discontinued reference still lands on a sale."),
    ("OE cross-references","Which aftermarket references map to which OE numbers, and at what brand tier."),
    ("Stock by warehouse","Plus carrier cut-off times, because next-day is the whole question for a garage.")],
  "proof": None,
  "faq": [("Can a voice agent really confirm fitment on the phone?","Only as well as your fitment table allows. Given a registration or VIN it decodes the variant and matches the part family, including build-date ranges. Where the table has no record for that variant it says so and hands over - it does not infer fitment from a similar model."),
    ("What about trade customers who call every day?","They are the ones who benefit most, because the call is short and repetitive: part, vehicle, stock, cut-off. The agent recognises the account from the number and skips the parts a regular caller does not need to hear."),
    ("Can it handle a caller who does not know their VIN?","Yes - it asks for the registration first, and falls back to make, model, year and engine, flagging that the answer is less certain than a VIN match. That caveat is spoken, not buried."),
    ("Does it work out of hours and at weekends?","Yes, and in this category that matters more than most: a lot of parts buying happens on a Saturday with the car already apart."),
    ("What does it need from our store to go live?","Read access to products and orders, your fitment and supersession tables, and stock by warehouse with cut-off times. If fitment lives in a supplier feed rather than your catalogue, we read the feed.")],
  "cta_h2": "Hear the agent take a fitment call",
  "cta_sub": "Bring a registration and a part number to the intro call. We&rsquo;ll run it against your own fitment data, live.",
  "cta_hand": "bring a reg, we&rsquo;ll try it"},

# ─────────────────────────────────────────────────────── ELECTRONICS
"electronics-tech": {
  "label": "Electronics &amp; Tech", "when": "before", "scene": "electronics",
  "title": "Voice AI for Electronics E-Commerce | Compatibility Calls | Sabato AI",
  "description": "Electronics buyers call about compatibility and spec differences. A managed voice agent that answers from your attribute matrix, then handles the returns queue behind it.",
  "h1": "&ldquo;Will it work with what I already own?&rdquo;",
  "sub": "Electronics buyers are comparing two models and one of them is already in their house. Sabato's agent reads the attribute matrix out loud, states the actual difference, and stops the wrong-model order before it ships.",
  "hand": "spec questions, answered from spec data",
  "call_q": "&ldquo;Will this dock work with a 2021 MacBook Pro and drive two 4K screens?&rdquo;",
  "call_meta": [("Detected intent","Compatibility check"),("Data pulled","Attribute matrix &middot; port spec"),("Outcome","Model swapped, order placed")],
  "band_eyebrow": "Why this category phones",
  "band_h2": "The specification is on the page. The answer isn&rsquo;t.",
  "band_copy": ["Electronics product pages are dense with attributes and still fail the only question that matters: will this work with the thing I own. The buyer can read &ldquo;HDMI 2.0&rdquo; and still not know whether their monitor will run at 120 Hz.",
                "So they call - and the cost of not answering is not a lost sale, it is a sold-then-returned unit, opened, unsellable as new, with the courier paid twice."],
  "rank_head": "What the inbound calls are about",
  "rank": ["Is it compatible with my existing device","What is the real difference between these two models","Is the newer version worth waiting for","Warranty terms and what voids them","Where is my order / can I return an opened item"],
  "questions_h2": "Five questions an electronics line hears every day - and what has to be true in your systems to answer them",
  "questions_intro": "This category punishes vagueness. Every answer resolves against a structured attribute, and where the attribute is missing on an older SKU the agent says so rather than reading marketing copy back to the caller.",
  "questions": [
    ("&ldquo;Will this dock drive two 4K monitors at 60 Hz?&rdquo;","Port specification and bandwidth attributes on the product, checked against the caller&rsquo;s stated setup.","attr.ports[] &middot; attr.max_resolution"),
    ("&ldquo;What is actually different between the Pro and the standard?&rdquo;","Attribute-level diff between the two SKUs, spoken as the differences only - not as a recital of both spec sheets.","sku.diff(a, b)"),
    ("&ldquo;Is a new version coming? I don&rsquo;t want to buy the old one.&rdquo;","Product lifecycle state and any announced successor, where you hold it. Where you don&rsquo;t, the agent says it doesn&rsquo;t know.","product.lifecycle_state"),
    ("&ldquo;If I open it and it&rsquo;s wrong, can I still send it back?&rdquo;","Your returns policy for opened electronics, per channel - the answer that most often differs from what the website implies.","returns.policy.opened"),
    ("&ldquo;Is the warranty with you or the manufacturer?&rdquo;","Warranty term and claim route on the product, including who the caller actually contacts in year two.","attr.warranty_months &middot; brand.claim_route")],
  "workflows": [("Pre-sales consultation","The compatibility call. Prevents the opened-box return.","/use-cases/pre-sales-consultation"),
                ("Managing returns","Opened electronics, triaged against policy before an RMA is issued.","/use-cases/managing-returns"),
                ("Where is my order","High-value parcels, so &ldquo;where is it&rdquo; carries more anxiety than most.","/use-cases/where-is-my-order"),
                ("Back-in-stock notification","Launch and allocation categories where the restock call is worth making.","/use-cases/back-in-stock-notification")],
  "transcript_meta": "Inbound &middot; 2 min 06 s &middot; language: English &middot; outcome: swapped to the correct model",
  "transcript": [("caller","I&rsquo;m looking at the USB-C dock, the one at ninety-nine. I&rsquo;ve got a 2021 MacBook Pro and two 4K monitors."),
    ("agent","That dock has two HDMI 2.0 outputs. On a 2021 MacBook Pro you would get both screens at 4K, but capped at 30 hertz on the second one - which most people notice straight away on a desktop."),
    ("caller","That would drive me mad."),
    ("agent","Then it&rsquo;s the Thunderbolt version instead. Both screens at 4K sixty, and it charges the laptop at ninety-six watts so you lose a cable. It&rsquo;s a hundred and seventy rather than ninety-nine."),
    ("caller","Does it need its own power supply?"),
    ("agent","It has one in the box. And to be clear about the returns side, since it&rsquo;s the more expensive one: opened is fine within thirty days as long as everything comes back with it."),
    ("caller","Fine. Let&rsquo;s do the Thunderbolt one.")],
  "data_h2": "The data reality behind a compatibility answer",
  "data_copy": "This category has more product data than any other and less of it structured. Compatibility written as prose in a PDF cannot be read by anything - not by an agent, and not by the AI search engines quoting your page.",
  "data_rows": [("Structured attributes","Ports, bandwidth, power, resolution - as fields, not as sentences in a description."),
    ("Compatibility matrix","Which SKUs work with which devices and at what level, including the caveats."),
    ("Lifecycle state","Current, end-of-life, successor announced. Prevents selling a buyer the outgoing model."),
    ("Returns policy for opened goods","Per channel and per category, because this is where the phone answer and the website most often disagree."),
    ("Warranty terms and claim route","Term, and who the customer actually contacts in year two.")],
  "proof": None,
  "faq": [("Can it answer compatibility questions accurately?","Where you hold structured attributes, yes - it reads them against what the caller describes. Where compatibility only exists as prose inside a PDF, it cannot, and it hands over instead of paraphrasing. That gap is worth knowing about before a pilot, not after."),
    ("Will it recommend a more expensive model?","It will recommend the model that answers the question, which sometimes costs more and sometimes costs less. An agent that always upsells stops being trusted, and in this category the buyer is usually comparing you to a spec sheet they already have open."),
    ("What about the returns queue after the sale?","That is the second workflow on this page for a reason. Opened electronics returns are expensive, and the agent triages against your actual policy rather than the one the website implies."),
    ("Does it handle technical callers?","Reasonably - it stays in specifics and hands over when the caller goes past what your data covers. It does not bluff, which is the failure mode technical callers detect fastest."),
    ("What does it need to go live?","Read access to products and orders, your attribute data, and your returns policy for opened goods. If attributes are thin on older SKUs we will tell you which ones before you launch.")],
  "cta_h2": "Hear the agent take a compatibility call",
  "cta_sub": "Bring your hardest spec question to the intro call. We&rsquo;ll run it against your own attribute data.",
  "cta_hand": "bring your hardest spec question"},

# ─────────────────────────────────────────────────────── FURNITURE
"furniture-home": {
  "label": "Furniture &amp; Home", "when": "before", "scene": "furniture",
  "title": "Voice AI for Furniture E-Commerce | Delivery &amp; Dimensions | Sabato AI",
  "description": "Furniture buyers call about dimensions, access and delivery slots. A managed voice agent that answers from your product data and delivery calendar, 24/7.",
  "h1": "It fits the room. The question is whether it fits the stairs.",
  "sub": "Furniture buyers have measured the alcove. What they can&rsquo;t work out is the turn on the landing, the delivery window, and whether anyone takes the old sofa away. Sabato's agent answers all three.",
  "hand": "the sale stalls on access, not on taste",
  "call_q": "&ldquo;Will the three-seater get up a turning staircase? And can you take the old one?&rdquo;",
  "call_meta": [("Detected intent","Access + delivery"),("Data pulled","Packed dims &middot; delivery calendar"),("Outcome","Slot booked, removal added")],
  "band_eyebrow": "Why this category phones",
  "band_h2": "A sofa is a logistics decision that happens to look like a purchase.",
  "band_copy": ["The buyer has decided on the sofa. What stops the order is the doorway, the lift, the Tuesday they are actually at home, and whether the old one gets taken away. None of that is on the product page, and all of it is knowable.",
                "Get it wrong and the failure is expensive in a way clothing returns never are: a two-person crew, a wasted slot, and a piece of furniture that comes back to a warehouse as a one-off."],
  "rank_head": "What the inbound calls are about",
  "rank": ["Dimensions and whether it will get in","Delivery slot, and can I change it","Assembly, and does anyone take the old one","Lead time on a made-to-order piece","Fabric, finish and whether a sample is possible"],
  "questions_h2": "Five questions a furniture line hears every day - and what has to be true in your systems to answer them",
  "questions_intro": "This category needs two things most catalogues hold badly: packed dimensions as distinct from assembled dimensions, and a delivery calendar the phone can actually read.",
  "questions": [
    ("&ldquo;Will it get up a turning staircase?&rdquo;","Packed dimensions - not assembled - plus whether the piece separates, which is the fact that decides most access questions.","product.packed_dims &middot; product.modular"),
    ("&ldquo;When can you deliver, and can I pick the day?&rdquo;","Live two-person delivery calendar for the caller&rsquo;s postcode, booked on the call rather than confirmed by email later.","delivery.slots(postcode)"),
    ("&ldquo;Do you take the old sofa away?&rdquo;","Removal service availability by area and its price, added to the order while the caller is still on the line.","service.removal.by_area"),
    ("&ldquo;It says made to order - how long really?&rdquo;","Production lead time on the specific fabric and frame combination, not the catalogue-wide figure.","variant.production_days"),
    ("&ldquo;Can I see the fabric before I commit?&rdquo;","Swatch availability for that fabric, dispatched on the call - the cheapest thing you can do to prevent a colour return.","swatch.available &middot; swatch.sku")],
  "workflows": [("Pre-sales consultation","Dimensions, access and finish. The questions that decide a four-figure order.","/use-cases/pre-sales-consultation"),
                ("Where is my order","Long lead times mean more status calls per order than any other category.","/use-cases/where-is-my-order"),
                ("Post-delivery feedback","Damage and assembly problems caught while they are still fixable.","/use-cases/post-delivery-feedback"),
                ("Qualify &amp; collect for quote","Multi-piece and contract enquiries captured properly the first time.","/use-cases/qualify-and-collect-for-quote")],
  "transcript_meta": "Inbound &middot; 2 min 22 s &middot; language: English &middot; outcome: slot booked, removal added",
  "transcript": [("caller","I want the three-seater in the grey, but I&rsquo;m on the first floor and the staircase turns."),
    ("agent","Let me check the packed size rather than the assembled one - that&rsquo;s the number that matters. It ships in two boxes, the largest is 205 by 96 by 82 centimetres, and the legs come off separately."),
    ("caller","Two boxes is better than I thought."),
    ("agent","It usually is on this model. If your landing turn is at least a metre wide it goes up without trouble. Do you know roughly?"),
    ("caller","About that, yes. What about delivery?"),
    ("agent","Two-person delivery in your postcode, next available is Thursday the fourteenth, then the Tuesday after. Both all-day, with a two-hour window texted the night before."),
    ("caller","Tuesday. And can you take the old sofa?"),
    ("agent","Yes - thirty-five pounds in your area, and the crew takes it on the same visit. I&rsquo;ll add it and book the Tuesday.")],
  "data_h2": "The data reality behind a furniture answer",
  "data_copy": "The two fields that matter most in this category are the two most often missing: packed dimensions, and a delivery calendar something other than a human can read.",
  "data_rows": [("Packed vs assembled dimensions","Both, as separate fields. Access questions are answered by the first and almost never by the second."),
    ("Delivery calendar by postcode","Live slots for two-person delivery, bookable on the call."),
    ("Removal and assembly services","Availability by area and price, so they can be added while the caller is deciding."),
    ("Production lead times","Per fabric and frame combination, not a catalogue-wide average."),
    ("Swatch inventory","Which fabrics can be sampled and how fast, because a swatch is cheaper than a returned sofa.")],
  "proof": None,
  "faq": [("Can it really answer whether furniture will fit up a staircase?","It gives the caller the packed dimensions and whether the piece separates, which is what the question actually turns on. It does not survey the house - it hands the buyer the numbers they need and flags when the answer is marginal."),
    ("Can it book a delivery slot on the call?","Yes, where your delivery calendar is readable by an API. That is the single highest-value integration in this category, because a slot booked on the call is a slot that does not become three emails."),
    ("What about made-to-order lead times?","It reads the production time for the specific fabric and frame the caller is asking about. Catalogue-wide lead times are where furniture merchants generate most of their status calls."),
    ("Does it handle the post-delivery problems too?","Damage and assembly issues route to a human with the order context attached. The agent is useful for catching them early, not for resolving a damage claim."),
    ("What does it need to go live?","Products with packed dimensions, your delivery calendar, and your service list for removal and assembly. Most furniture merchants have the third in a spreadsheet, which is fine.")],
  "cta_h2": "Hear the agent take a delivery and access call",
  "cta_sub": "We&rsquo;ll run it against your own dimensions and delivery calendar on the intro call.",
  "cta_hand": "twenty minutes, no deck"},

# ─────────────────────────────────────────────────────── INDUSTRIAL
"industrial-b2b": {
  "label": "Industrial &amp; B2B", "when": "before", "scene": "industrial",
  "title": "Voice AI for Industrial &amp; B2B E-Commerce | Quotes &amp; Spec | Sabato AI",
  "description": "Industrial buyers call for spec confirmation, contract pricing and lead times. A managed voice agent that reads your ERP and captures quote enquiries properly.",
  "h1": "The order is small. The consequence of getting it wrong isn&rsquo;t.",
  "sub": "Industrial buyers ring to confirm a tolerance, a certification, a contract price or a lead time before they commit a line down. Sabato's agent answers from the ERP and captures the quote enquiry with the fields your team actually needs.",
  "hand": "spec first, price second, always",
  "call_q": "&ldquo;Is the 316 stainless version certified to 3.1, and what&rsquo;s my contract price on 200?&rdquo;",
  "call_meta": [("Detected intent","Spec + contract pricing"),("Data pulled","Cert docs &middot; account price list"),("Outcome","Quote issued same call")],
  "band_eyebrow": "Why this category phones",
  "band_h2": "Nobody specifies a fastener from a product photograph.",
  "band_copy": ["Industrial buying is verification. The buyer knows what they need, and rings to confirm the grade, the certification, the tolerance and the price on their account before they commit - because the cost of a wrong part is a stopped line, not a return.",
                "These calls are short, repetitive and highly qualified. They are also the ones that go to voicemail at 6pm, which is when maintenance teams tend to discover what they are missing."],
  "rank_head": "What the inbound calls are about",
  "rank": ["Spec and material confirmation","My contract price on this quantity","Certification and documentation","Lead time and whether it is stocked","Where is my order, we have a line down"],
  "questions_h2": "Five questions an industrial line hears every day - and what has to be true in your systems to answer them",
  "questions_intro": "Account-specific pricing makes this category different: the agent has to recognise who is calling before it can answer anything about price. Everything else resolves against the ERP.",
  "questions": [
    ("&ldquo;Is this the 316 grade, and to what tolerance?&rdquo;","Material grade and tolerance as structured attributes, and the standard they are certified against.","attr.material_grade &middot; attr.tolerance_class"),
    ("&ldquo;What&rsquo;s my price on two hundred?&rdquo;","The caller&rsquo;s account recognised from the number, then their contract price list at that quantity break - not list price.","account.by_phone &middot; pricelist.break(qty)"),
    ("&ldquo;Can you send the 3.1 certificate?&rdquo;","The certification document for that batch, emailed during the call as the document itself.","docs.cert_3_1 &middot; batch.id"),
    ("&ldquo;Is it stocked, or is that a lead time?&rdquo;","Free stock net of allocations, plus the supplier lead time when the item is not held.","erp.free_stock &middot; supplier.lead_days"),
    ("&ldquo;We have a line down - what can you get here tomorrow?&rdquo;","Free stock across warehouses plus the expedite routes available on that account, with a human brought in for anything needing a special.","stock.free_by_wh &middot; expedite.options")],
  "workflows": [("Qualify &amp; collect for quote","The volume workflow here. Enquiries captured with the fields a quote actually needs.","/use-cases/qualify-and-collect-for-quote"),
                ("Pre-sales consultation","Spec and certification confirmation before the order is committed.","/use-cases/pre-sales-consultation"),
                ("Where is my order","A stopped production line asks differently, and needs an answer at once.","/use-cases/where-is-my-order"),
                ("Checkout summary via text","Part, grade, certification and price confirmed in writing on a purchase-order trail.","/use-cases/checkout-summary-via-text")],
  "transcript_meta": "Inbound &middot; 1 min 44 s &middot; language: English &middot; outcome: quote issued during the call",
  "transcript": [("caller","Morning - I need the M10 socket caps, the stainless ones, in 316 not 304."),
    ("agent","I have you as Harlow Engineering from the number, is that right?"),
    ("caller","That&rsquo;s us."),
    ("agent","Then on your account the 316 M10 by 40 is one pound eighteen each up to a hundred, and ninety-four pence from two hundred. Both stocked in Leeds."),
    ("caller","Two hundred then. Do they come with a 3.1?"),
    ("agent","They do - I&rsquo;ll email the certificate for the current batch as soon as we finish, along with the quote."),
    ("caller","And if I order this morning?"),
    ("agent","Cut-off is two o&rsquo;clock for next day on your postcode, so tomorrow before noon. Shall I raise the quote against your usual purchase-order reference?"),
    ("caller","Yes, do that.")],
  "data_h2": "The data reality behind an industrial answer",
  "data_copy": "The distinguishing requirement in this category is account recognition. An agent that cannot tell who is calling cannot answer the price question, and price is in most of these calls.",
  "data_rows": [("Account identification","Phone number to account, so contract pricing and terms are available from the first sentence."),
    ("Contract price lists","Per account, with quantity breaks. List price is the wrong answer to a trade caller."),
    ("Material and tolerance attributes","Structured, with the standard they certify against."),
    ("Certification documents","By batch, retrievable and emailable during the call."),
    ("Free stock net of allocation","Not gross stock - the number the ERP will actually honour against a purchase order.")],
  "proof": None,
  "faq": [("Can it quote contract prices to trade accounts?","Where it can identify the account - usually from the calling number - it reads that account&rsquo;s price list including quantity breaks. Unrecognised callers get list price and an offer to have someone call back, rather than a guess."),
    ("Can it send certification documents on the call?","Yes, where the documents are stored against the batch or product and are reachable. Emailing the certificate during the call removes one of the most common follow-up tasks in this category."),
    ("Does it replace our internal sales desk?","No. It takes the repetitive verification calls - spec, price, stock, lead time - so the desk handles specials, technical escalation and the accounts that need a relationship. The agent hands over with full context."),
    ("What about out-of-hours calls from maintenance teams?","That is where a lot of the value sits. Breakdowns do not respect opening hours, and a stocked-or-not answer at seven in the evening is often the difference between your order and a competitor&rsquo;s."),
    ("What does it need to go live?","ERP read access for stock and pricing, your account-to-number mapping, and your certification documents. The account mapping is the one most merchants have to assemble.")],
  "cta_h2": "Hear the agent take a trade spec call",
  "cta_sub": "Bring a real part and a real account to the intro call. We&rsquo;ll run it against your own pricing and stock.",
  "cta_hand": "bring a real part number"},

# ─────────────────────────────────────────────────────── OUTDOOR
"outdoor-garden": {
  "label": "Outdoor &amp; Garden", "when": "mixed", "scene": "outdoor",
  "title": "Voice AI for Outdoor &amp; Garden E-Commerce | Seasonal Call Peaks | Sabato AI",
  "description": "Garden retail has the sharpest seasonal call peak in e-commerce. A managed voice agent that absorbs it - sizing, spares, restock dates and delivery.",
  "h1": "Your call volume is a weather forecast.",
  "sub": "Garden demand arrives in a handful of warm weekends and disappears again. Sabato's agent absorbs the peak without a seasonal hire, handles the spares and sizing calls, and rings back the customers who wanted the sold-out thing.",
  "hand": "the peak is the problem, not the average",
  "call_q": "&ldquo;What size mower for about 800 square metres, and is the sit-on back in stock yet?&rdquo;",
  "call_meta": [("Detected intent","Sizing + restock"),("Data pulled","Cutting width &middot; inbound PO"),("Outcome","Callback set for restock")],
  "band_eyebrow": "Why this category phones",
  "band_h2": "Twelve weeks of demand, and a phone line staffed for fifty-two.",
  "band_copy": ["Garden retail concentrates most of its year into a short season, and the calls concentrate harder still - the first warm Saturday produces a volume no permanently staffed line is sized for, and abandoned calls in a peak skew towards buyers who were ready to spend.",
                "The rest of the year the same line handles spares: a part number off a machine bought four seasons ago, which is a lookup, not a conversation."],
  "rank_head": "What the inbound calls are about",
  "rank": ["Which size or model for my plot","Is it back in stock, and when","Spare part for a machine I already own","Delivery timing before the weekend","Assembly, servicing and winter storage"],
  "questions_h2": "Five questions a garden line hears every day - and what has to be true in your systems to answer them",
  "questions_intro": "Two very different jobs share one phone line here: seasonal sizing calls from new buyers, and spares lookups from owners. The data behind them is different, and both are answerable.",
  "questions": [
    ("&ldquo;What size mower for eight hundred square metres?&rdquo;","Cutting width and recommended plot range on the product, matched to the area and terrain the caller describes.","attr.cutting_width_cm &middot; attr.plot_max_m2"),
    ("&ldquo;When is it back in stock?&rdquo;","Inbound purchase order date checked against how much season is left - a restock landing in September is a different answer from one landing in May.","po.expected_at &middot; season.cutoff"),
    ("&ldquo;I need the blade for a model I bought in 2021.&rdquo;","Spare-part compatibility by machine model and year, including superseded part numbers.","spares.by_model(year) &middot; part.superseded_by[]"),
    ("&ldquo;Will it arrive before the weekend?&rdquo;","Carrier cut-off against the caller&rsquo;s postcode - the question that decides the order in a category driven by two dry days.","carrier.cutoff &middot; stock.by_wh"),
    ("&ldquo;Does it need servicing, and do you do it?&rdquo;","Service interval on the product and whether you offer it, so the answer is a booking rather than a maybe.","attr.service_interval &middot; service.available")],
  "workflows": [("Pre-sales consultation","Sizing for the plot. The seasonal call that converts.","/use-cases/pre-sales-consultation"),
                ("Back-in-stock notification","Sold-out season lines, called back the day stock lands.","/use-cases/back-in-stock-notification"),
                ("Where is my order","Peak-week volume, answered without a seasonal hire.","/use-cases/where-is-my-order"),
                ("Managing returns","End-of-season returns triaged against policy.","/use-cases/managing-returns")],
  "transcript_meta": "Inbound &middot; 1 min 49 s &middot; language: English &middot; outcome: restock callback booked",
  "transcript": [("caller","I&rsquo;m after a mower for about eight hundred square metres, and it&rsquo;s got a slope at the back."),
    ("agent","At eight hundred with a slope I&rsquo;d be looking at the self-propelled models rather than the push ones - the 46 centimetre cut is the one most people take for that size."),
    ("caller","I was actually looking at the sit-on, but it says out of stock."),
    ("agent","It is, and I won&rsquo;t pretend otherwise. There&rsquo;s a delivery due on the eighteenth, so about two weeks. I can ring you the morning it lands if you want first refusal."),
    ("caller","Yes, do that. Would the 46 do the job in the meantime?"),
    ("agent","It would, comfortably. And if you want it for this weekend the cut-off for Friday delivery on your postcode is Wednesday at two."),
    ("caller","Let me think about it. Book the callback for the sit-on though."),
    ("agent","Booked for the eighteenth. I&rsquo;ll text you the link to the 46 as well, in case the weather turns first.")],
  "data_h2": "The data reality behind a garden answer",
  "data_copy": "The seasonal shape is the whole problem here. Concurrency matters more than in any other category on this list: the agent takes every call at once rather than queueing them, which is exactly what a peak Saturday needs.",
  "data_rows": [("Sizing attributes","Cutting width, plot range, power - as fields, so a plot size maps to a model."),
    ("Inbound purchase orders","Expected dates by variant, so a restock promise is a date rather than a shrug."),
    ("Spares compatibility","By machine model and year, with superseded part numbers followed."),
    ("Carrier cut-offs by postcode","In a weather-driven category, &ldquo;before the weekend&rdquo; is the buying decision."),
    ("Service availability","Intervals and whether you service, so the answer is a booking.")],
  "proof": None,
  "faq": [("What happens when the season peaks?","Concurrency is the point: the agent answers every call simultaneously rather than queueing them. Peak Saturdays are when abandoned calls spike, and abandoned calls in this category skew towards buyers who were ready to spend."),
    ("Can it handle spare-part lookups for old machines?","Where you hold spares compatibility by model and year, yes - including following superseded part numbers. That is the off-season half of this line&rsquo;s work and it is almost entirely lookup."),
    ("Is it worth it if we are only busy three months a year?","That is the honest question for this category. A voice layer has no seasonal hiring lead time and no training cost, which is what makes a short season workable - but if your peak is small, we will say so on the intro call rather than sell you one."),
    ("Can it call people back when stock lands?","Yes, and in garden retail it is worth more than an email, because season demand is time-boxed. The agent rings, confirms, and takes the order on the same call."),
    ("What does it need to go live?","Products with sizing attributes, inbound purchase order dates, spares compatibility and your carrier cut-offs. The spares data is usually the one that needs work.")],
  "cta_h2": "Hear the agent take a peak-Saturday call",
  "cta_sub": "We&rsquo;ll run it against your own catalogue and restock dates on the intro call - before the season starts, ideally.",
  "cta_hand": "before the season, not during"},

# ─────────────────────────────────────────────────────── FASHION
"fashion-apparel": {
  "label": "Fashion &amp; Apparel", "when": "after", "scene": "fashion",
  "title": "Voice AI for Fashion &amp; Apparel E-Commerce | Sabato AI",
  "description": "Fashion buyers rarely phone before buying - they phone after. A managed voice agent that handles WISMO, exchanges and restock calls from live order data.",
  "h1": "Fashion buyers don&rsquo;t phone before they buy. They phone after.",
  "sub": "Nobody calls to ask about a t-shirt. They call because the parcel is late, the size was wrong, or the piece they wanted came back into stock. That queue is post-purchase, it is seasonal, and it is the one that breaks.",
  "hand": "here the call is the aftermath, not the sale",
  "call_q": "&ldquo;My order was supposed to arrive Tuesday and the tracking hasn&rsquo;t moved since Friday.&rdquo;",
  "call_meta": [("Detected intent","Order status &middot; late parcel"),("Data pulled","Carrier events &middot; order 48213"),("Outcome","Answered, exchange offered")],
  "band_eyebrow": "Why this category phones",
  "band_h2": "The call arrives after the money moved, which is why it costs more than it looks.",
  "band_copy": ["A fashion buyer will happily choose a jacket without speaking to anyone. The product page does its job. Then the parcel is late, or the 12 fitted like a 10, and the same buyer wants a human - quickly, and usually during a peak week when the queue is already at its worst.",
                "This is deflection and retention work, not conversion work. We are honest about that: on a &euro;40 t-shirt there is no call to win. On the returns and delivery queue behind it, there is a real cost to remove."],
  "rank_head": "What the inbound calls are about",
  "rank": ["Where is my order / late delivery","Size exchange or return","Refund status and when the money lands","Back in stock: when, and reserve it","Promo code, discount and payment issues"],
  "questions_h2": "Five questions a fashion line hears every day - and what has to be true in your systems to answer them",
  "questions_intro": "None of these need product expertise. All of them need a live, correct record. That is the whole job in this category: read the right field, out loud, at eleven at night in the caller&rsquo;s language.",
  "questions": [
    ("&ldquo;Where is my order, it was supposed to be here Tuesday?&rdquo;","Carrier tracking events on the order, with the exception reason spoken plainly rather than as a status code.","carrier.events &middot; order.promised_date"),
    ("&ldquo;Can I exchange this for the next size up?&rdquo;","Return eligibility window, plus whether that size is in stock right now - so the answer is an exchange, not a refund.","returns.window &middot; variant.available"),
    ("&ldquo;I sent it back two weeks ago, where is my refund?&rdquo;","Return receipt scan at the warehouse and the refund state on the payment provider.","rma.received_at &middot; payment.refund_state"),
    ("&ldquo;When is this coming back in stock?&rdquo;","Inbound purchase order date for the variant, and a callback booked for the day it lands.","po.expected_at &middot; variant.id"),
    ("&ldquo;Does this run small? I&rsquo;m usually a 12.&rdquo;","Garment measurements per size where you hold them, and an explicit hand-off when you don&rsquo;t - the one question in this category the agent should refuse to guess.","variant.measurements &middot; fallback: human")],
  "workflows": [("Where is my order","The volume workflow in fashion. Carrier events read out loud, exceptions explained.","/use-cases/where-is-my-order"),
                ("Managing returns","Eligibility checked against policy, exchange offered before refund.","/use-cases/managing-returns"),
                ("Back-in-stock notification","Calls the customers who wanted it, instead of an email in a spam folder.","/use-cases/back-in-stock-notification"),
                ("Post-delivery feedback","Catches the problem while it is still fixable, and earns the review.","/use-cases/post-delivery-feedback")],
  "transcript_meta": "Inbound &middot; 1 min 52 s &middot; language: English &middot; outcome: exchange booked, no refund",
  "transcript": [("caller","Hi, I ordered a coat last week, it was meant to arrive Tuesday and the tracking hasn&rsquo;t moved since Friday."),
    ("agent","Let me look. Order ending 8213, the coat in navy - it&rsquo;s at the Milan depot and it was held there on Saturday because of a failed delivery attempt at the address. It&rsquo;s scheduled to go out again tomorrow morning."),
    ("caller","Nobody came on Saturday."),
    ("agent","That happens more than it should. I can either leave it on tomorrow&rsquo;s round, or reroute it to a pickup point near you - there&rsquo;s one about four hundred metres from the delivery address."),
    ("caller","The pickup point. And actually - if the size is wrong when it turns up, how does that work?"),
    ("agent","Thirty days from delivery. If it&rsquo;s the size rather than the coat, I&rsquo;d do an exchange instead of a return: the navy is in stock in both the size above and below, so it ships the day we scan yours back."),
    ("caller","Good. Do the pickup point then."),
    ("agent","Rerouted, and I&rsquo;ll text you the pickup code when it arrives. Anything else on this one?")],
  "data_h2": "The data reality behind a fashion answer",
  "data_copy": "This category asks less of your product data and more of your operational data. The failure mode is not a wrong recommendation - it is a confident wrong delivery date, which turns one annoyed customer into two calls.",
  "data_rows": [("Carrier tracking events","Raw events, not a status label, so an exception can be explained rather than recited."),
    ("Order promise date","What the customer was actually told at checkout, which is often not what the carrier thinks."),
    ("Returns window and policy","Per channel and per promotion, so the answer on the phone matches the portal."),
    ("Variant availability","Live, so an exchange can be offered instead of a refund while the buyer is on the line."),
    ("Inbound purchase orders","Expected dates by variant, for back-in-stock calls that are worth making.")],
  "proof": None,
  "faq": [("Do fashion customers actually call?","Not usually before buying - that is the honest answer, and it is why this page leads with post-purchase. They call when a parcel is late, when a size is wrong, or when a refund has not landed. In peak weeks that queue is the one that overflows."),
    ("Is voice AI worth it if our average order value is low?","It depends on your call volume, not your order value. If the post-purchase queue is large and seasonal, the case is deflection and retention. If it is small and steady, self-service is probably enough and we will say so on the intro call."),
    ("Can the agent handle a size or fit question?","Only where you hold garment measurements per size. Where you do not, it hands over rather than guessing - fit is the one question in this category where a confident wrong answer converts directly into a return."),
    ("What happens during a sale week when volume triples?","Concurrency is the point. The agent takes every call at once rather than queueing them, which is when abandoned calls in fashion usually spike - and abandoned calls skew towards the customers with a problem."),
    ("Does it work in more than one language?","Yes, and in fashion that matters more than in most categories, because cross-border share is high. The agent detects the caller&rsquo;s language on the first turn and stays in it, including the follow-up message.")],
  "cta_h2": "Hear the agent take a late-parcel call",
  "cta_sub": "We&rsquo;ll run it against your own order data on the intro call - your carrier, your returns policy, your peak-week volume.",
  "cta_hand": "twenty minutes, no deck"},

# ─────────────────────────────────────────────────────── HEALTH
"health-wellness": {
  "label": "Health &amp; Wellness", "when": "after", "scene": "health",
  "title": "Voice AI for Health &amp; Wellness E-Commerce | Subscriptions &amp; WISMO | Sabato AI",
  "description": "Health and wellness calls are mostly subscriptions, deliveries and returns on opened goods. A managed voice agent that handles them - and refuses to give health advice.",
  "h1": "Most of these calls are about a subscription, not a product.",
  "sub": "Skip this month, change the address, where is it, can I send it back. Sabato's agent handles the repeat-order queue that wellness brands run on - and hands anything resembling health advice straight to a human.",
  "hand": "the agent never gives health advice",
  "call_q": "&ldquo;I need to skip next month&rsquo;s delivery and change the address.&rdquo;",
  "call_meta": [("Detected intent","Subscription change"),("Data pulled","Sub 7741 &middot; next charge date"),("Outcome","Skipped, address updated")],
  "band_eyebrow": "Why this category phones",
  "band_h2": "A subscription is a relationship with a billing date, and people ring about billing dates.",
  "band_copy": ["Wellness brands run on repeat orders, and repeat orders generate a specific, high-volume, low-complexity call: pause it, skip it, move it, change the card, change the address. Every one of those is a database write that someone is currently doing by hand.",
                "The second queue is returns on opened goods, where policy is narrower than in most categories and the answer on the phone has to match the answer in the portal exactly."],
  "rank_head": "What the inbound calls are about",
  "rank": ["Skip, pause or cancel a subscription","Where is my order / missed delivery","Can I return an opened item","Change the delivery date, address or card","Ingredients, allergens and suitability"],
  "questions_h2": "Five questions a wellness line hears every day - and what has to be true in your systems to answer them",
  "questions_intro": "Four of these are subscription and logistics lookups. The fifth is the one the agent must not answer on its own, and the boundary between them is the most important thing on this page.",
  "questions": [
    ("&ldquo;Can I skip next month?&rdquo;","Subscription state and next charge date, with the skip written back on the call rather than promised by email.","sub.next_charge_at &middot; sub.skip()"),
    ("&ldquo;I&rsquo;m away - can it come a week later, to a different address?&rdquo;","Delivery date and address on the next scheduled order, updated before the cut-off.","sub.next_order.date &middot; sub.address"),
    ("&ldquo;I opened it and it doesn&rsquo;t agree with me. Can I send it back?&rdquo;","Your returns policy for opened consumables, which is narrower than most categories and must match the portal exactly.","returns.policy.opened_consumable"),
    ("&ldquo;Does this contain any dairy?&rdquo;","The structured allergen and ingredient list on the product, read verbatim - a list, not an interpretation.","attr.allergens[] &middot; attr.ingredients"),
    ("&ldquo;Can I take this with my medication?&rdquo;","Nothing. This is the hand-off. The agent does not answer health questions, and says so plainly before transferring.","escalate: human &middot; no_advice_policy")],
  "workflows": [("Where is my order","Repeat deliveries mean repeat status calls. The volume workflow here.","/use-cases/where-is-my-order"),
                ("Managing returns","Opened consumables, checked against a narrower policy than most categories.","/use-cases/managing-returns"),
                ("Post-delivery feedback","Catches a problem with a repeat order before the next one ships.","/use-cases/post-delivery-feedback"),
                ("Back-in-stock notification","Regulars who want the thing they always buy, the day it returns.","/use-cases/back-in-stock-notification")],
  "transcript_meta": "Inbound &middot; 1 min 31 s &middot; language: English &middot; outcome: subscription skipped, address changed",
  "transcript": [("caller","Hi - I&rsquo;ve got a monthly order and I need to skip the next one."),
    ("agent","I can do that. I have a subscription on this number due to charge on the third. Skip that one and the next would be the third of the following month."),
    ("caller","Perfect. And I&rsquo;m moving, so the one after should go somewhere else."),
    ("agent","I can update the address now and it will apply from that order onwards. Whenever you&rsquo;re ready."),
    ("caller","It&rsquo;s 14 Ashfield Road, Bristol, BS6 5AQ."),
    ("agent","Saved. So: nothing on the third, then the usual order to Ashfield Road the month after."),
    ("caller","One more thing - I take a blood thinner, is this all right alongside it?"),
    ("agent","That&rsquo;s not something I&rsquo;ll answer, and I&rsquo;d rather say so than guess. I&rsquo;m putting you through to the team now - and it&rsquo;s worth asking your pharmacist as well.")],
  "data_h2": "The data reality behind a wellness answer",
  "data_copy": "The hard boundary in this category is not technical, it is editorial. The agent reads ingredient lists; it does not interpret them. Anything that sounds like a health question is handed over, and that rule is enforced in the workflow rather than left to judgement.",
  "data_rows": [("Subscription state","Next charge date, skip and pause actions writable on the call, not queued for a human."),
    ("Delivery address and date","On the next scheduled order, editable before the cut-off."),
    ("Returns policy for opened consumables","Narrower than most categories, and it must match the portal exactly."),
    ("Structured allergens and ingredients","As a list to be read verbatim, never summarised or interpreted."),
    ("Escalation rule","Any health, dosage or interaction question goes to a human. Enforced, not advisory.")],
  "proof": None,
  "faq": [("Will the agent give health advice?","No. Ingredient and allergen lists are read verbatim from your product data; anything about dosage, interactions, conditions or suitability is handed to a human, and the agent says plainly that it is not going to answer. That boundary is enforced in the workflow, not left to the model&rsquo;s judgement."),
    ("Can it change or cancel a subscription on the call?","Yes, where your subscription platform allows writes - skip, pause, change date, change address. That is the highest-volume request in this category and the one most often handled by hand today."),
    ("What about returns on opened consumables?","It checks your actual policy, which in this category is usually narrower than elsewhere. The important part is that the phone answer and the portal answer are the same one."),
    ("Is this compliant for a regulated category?","We are not lawyers and will not pretend to be. What we can say is that the agent is constrained to reading your own product data and cannot generate health claims, and every call is transcribed for review. Your regulatory position is yours to confirm."),
    ("What does it need to go live?","Subscription platform access, order and product data with structured allergen fields, and your returns policy for opened goods.")],
  "cta_h2": "Hear the agent handle a subscription call",
  "cta_sub": "We&rsquo;ll run it against your own subscription data on the intro call - including where it refuses to answer.",
  "cta_hand": "including where it says no"},

# ─────────────────────────────────────────────────────── SPORTS
"sports-fitness": {
  "label": "Sports &amp; Fitness", "when": "after", "scene": "sports",
  "title": "Voice AI for Sports &amp; Fitness E-Commerce | Sizing &amp; Delivery | Sabato AI",
  "description": "Sports retail splits in two: low-ticket kit that calls after buying, and heavy equipment that calls before. A managed voice agent that handles both queues.",
  "h1": "Two catalogues, one phone line.",
  "sub": "The running vest generates a returns call. The rowing machine generates a delivery-and-access call before anyone buys it. Sabato's agent handles both, and treats them as the different jobs they are.",
  "hand": "kit calls after, equipment calls before",
  "call_q": "&ldquo;Is the rower going to fit through a standard door, and who carries it upstairs?&rdquo;",
  "call_meta": [("Detected intent","Dimensions + delivery"),("Data pulled","Packed dims &middot; delivery type"),("Outcome","Slot booked to room of choice")],
  "band_eyebrow": "Why this category phones",
  "band_h2": "Most of the catalogue never generates a call. The heavy end generates nothing but.",
  "band_copy": ["Sports retail is really two businesses sharing a phone number. Apparel and consumables behave like fashion - the calls arrive after the parcel, about size exchanges and late deliveries. Heavy equipment behaves like furniture: nobody spends four figures on a treadmill without asking about the doorway and the delivery.",
                "Treating them as one queue is why the line feels unmanageable. They need different answers from different systems, which is exactly what a workflow split is for."],
  "rank_head": "What the inbound calls are about",
  "rank": ["Where is my order / late delivery","Size exchange on apparel and footwear","Equipment dimensions, weight and access","Assembly, delivery to room, old-kit removal","Spare parts and warranty on equipment"],
  "questions_h2": "Five questions a sports line hears every day - and what has to be true in your systems to answer them",
  "questions_intro": "The first two come from the apparel half of the catalogue and the last three from the equipment half. Same line, different data behind them.",
  "questions": [
    ("&ldquo;Where is my order?&rdquo;","Which half of the catalogue it came from decides the answer: a parcel carrier event, or a two-person delivery slot that has to be rebooked.","product.delivery_type &middot; carrier.events"),
    ("&ldquo;These trainers come up narrow - can I swap the size?&rdquo;","Fitting width on the model as well as the size, plus live availability in the wide option - narrow is often a fitting problem, not a size one.","variant.fitting_width &middot; returns.window"),
    ("&ldquo;Will the rower fit through a standard doorway?&rdquo;","Packed dimensions and weight, plus whether it folds - the three facts that decide a heavy-equipment order.","product.packed_dims &middot; attr.folds"),
    ("&ldquo;Do you bring it to the room, or leave it at the door?&rdquo;","Delivery service level for that product: kerbside, threshold, or room of choice with assembly.","product.delivery_type &middot; service.assembly"),
    ("&ldquo;The console on my treadmill has failed - is it covered?&rdquo;","Warranty term by component and the parts availability for that model year.","attr.warranty_by_part &middot; spares.by_model")],
  "workflows": [("Where is my order","The apparel half of the catalogue. High volume, low complexity.","/use-cases/where-is-my-order"),
                ("Managing returns","Size exchanges on footwear and apparel, offered before refunds.","/use-cases/managing-returns"),
                ("Pre-sales consultation","The equipment half. Dimensions, access and delivery on a four-figure order.","/use-cases/pre-sales-consultation"),
                ("Back-in-stock notification","Sizes and season lines, called back rather than emailed.","/use-cases/back-in-stock-notification")],
  "transcript_meta": "Inbound &middot; 2 min 04 s &middot; language: English &middot; outcome: room-of-choice delivery booked",
  "transcript": [("caller","I&rsquo;m looking at the rower, but it&rsquo;s going in a spare room upstairs and I want to know if it&rsquo;ll get up there."),
    ("agent","Packed, it&rsquo;s 218 by 56 by 40 centimetres and 44 kilos, in one box. That goes through a standard doorway, but 44 kilos up a flight of stairs is a two-person job."),
    ("caller","That&rsquo;s what I was worried about."),
    ("agent","Then take the room-of-choice delivery rather than the standard one. Two people, they carry it to the room you want and take the packaging away. It&rsquo;s twenty-nine pounds on this item."),
    ("caller","And does it need assembling?"),
    ("agent","Minimal - the seat rail and the console, about twenty minutes. Assembly on the same visit is another twenty pounds if you&rsquo;d rather not."),
    ("caller","Do the delivery and the assembly."),
    ("agent","Both added. Next available in your postcode is Thursday week, with a two-hour window texted the night before.")],
  "data_h2": "The data reality behind a sports answer",
  "data_copy": "The split catalogue is the thing to get right. If equipment and apparel are treated as one product type, the agent will offer kerbside delivery on a treadmill and a two-person slot on a t-shirt.",
  "data_rows": [("Carrier tracking events","For the apparel half, where volume is highest and complexity lowest."),
    ("Returns window and live sizes","So a size problem becomes an exchange rather than a refund."),
    ("Packed dimensions and weight","For equipment. Weight matters as much as size once stairs are involved."),
    ("Delivery service level per product","Kerbside, threshold or room-of-choice - set on the product, not assumed."),
    ("Warranty by component and spares","Equipment fails by part, and the warranty usually differs by part.")],
  "proof": None,
  "faq": [("Our catalogue is mostly clothing - is this worth it?","Then your case is the post-purchase queue: deliveries, exchanges, refunds. It is the same argument as fashion. If that queue is large or spikes hard around sale weeks, there is cost to remove; if it is small and steady, we will tell you so."),
    ("Can it handle the heavy equipment side properly?","That is what the packed dimensions, weight and delivery-service-level fields are for. It answers the doorway and stairs question, then books the right delivery type - which is where most equipment orders actually stall."),
    ("Does it know when to offer an exchange instead of a refund?","Yes, where availability is live. Offering the adjacent size while the customer is on the phone is the single cheapest retention move in this category."),
    ("What about sale weeks and product drops?","Concurrency. Every call is answered at once rather than queued, which is when abandoned calls spike - and the abandoned ones skew towards customers with a problem."),
    ("What does it need to go live?","Orders and carrier data, live variant availability, and for equipment: packed dimensions, weight and delivery service level per product.")],
  "cta_h2": "Hear the agent take both kinds of call",
  "cta_sub": "Bring one apparel order and one equipment SKU to the intro call. They are different jobs and it shows.",
  "cta_hand": "two catalogues, one test"},
}
