#!/usr/bin/env python3
"""Contenuti italiani delle pagine settore.

Scritti in italiano, non tradotti dall'inglese: le domande che arrivano davvero
a un centralino italiano non sono la traduzione di quelle inglesi (il Conto
Termico, la targa, il 3.1, la zona climatica).

Come per la versione inglese, la variabile fra i nove settori è QUALI WORKFLOW
DOMINANO, non il sostantivo: nelle categorie ad alta considerazione si chiama
prima di comprare, in quelle a bassa considerazione dopo.

`alias` elenca le etichette con cui il footer nomina la categoria - il footer
Framer e le pagine autorali non usano sempre le stesse parole, e "Home
Improvement" è rimasto in inglese nel sorgente.
"""

INDUSTRIES_IT = {

"clima-e-riscaldamento": {
  "en": "home-improvement", "alias": ["Home Improvement", "Miglioramento Casa"],
  "label": "Clima e Riscaldamento", "when": "before", "scene": "hvac",
  "title": "Voice AI per E-Commerce di Clima e Riscaldamento | Sabato AI",
  "description": "Un agente vocale gestito che dimensiona l'unità, controlla la zona climatica e fissa il sopralluogo - dalle tue tabelle kW e dal tuo ERP. Attivo in due settimane.",
  "h1": "Chi compra clima e riscaldamento telefona prima di comprare.",
  "sub": "L'agente vocale gestito di Sabato dimensiona l'unità, controlla la zona climatica, dice cosa comprende davvero l'installazione - e fissa il sopralluogo mentre il cliente è ancora interessato.",
  "hand": "qui la chiamata è il configuratore",
  "call_q": "&ldquo;Ho 120 m&sup2; su un piano solo, fuori Milano - il 9 kW è quello giusto?&rdquo;",
  "call_meta": [("Intento rilevato","Dimensionamento + posa"),("Dati letti","Tabella kW &middot; zona E"),("Esito","Sopralluogo fissato")],
  "band_eyebrow": "Perché questa categoria telefona",
  "band_h2": "Una pompa di calore è una decisione di capitolato presa da chi il capitolato non ce l&rsquo;ha.",
  "band_copy": ["Nessuno compra 12 kW. Compra una casa: 120 m&sup2;, del 1978, piano unico, i radiatori che vorrebbe tenere, un CAP con una sua temperatura di progetto invernale. La scheda prodotto non può rispondere, quindi il cliente o telefona o se ne va.",
                "Quella chiamata non è assistenza. È l&rsquo;ultimo passo della vendita, e arriva in orario di ufficio su una linea già occupata da un installatore che chiede di una consegna."],
  "rank_head": "Di cosa parlano le chiamate in entrata",
  "rank": ["Quale unità per i miei metri quadri","Installazione: inclusa, chi la fa, quando","Prezzo e preventivo per l&rsquo;impianto completo","Detrazioni e documenti di certificazione","Tempi di consegna e dov&rsquo;è l&rsquo;ordine"],
  "questions_h2": "Sei domande che un centralino del clima sente ogni giorno - e cosa deve esserci nei tuoi sistemi per rispondere",
  "questions_intro": "Un agente vale quanto i dati che può leggere. Queste sono le coppie che contano nel riscaldamento e nel condizionamento: ogni domanda si risolve su un campo preciso, non su una conoscenza generica del settore.",
  "questions": [
    ("&ldquo;Che unità mi serve per 120 m&sup2; su un piano?&rdquo;","Tabella di dimensionamento kW/BTU incrociata con la zona climatica del CAP e l&rsquo;altezza soffitto dichiarata.","product.heating_capacity_kw &middot; zone.design_temp"),
    ("&ldquo;L&rsquo;installazione è compresa, e chi la fa?&rdquo;","Copertura installatori per CAP più il codice servizio di posa e il suo tempo di attesa attuale.","installers.by_cap &middot; sku.INSTALL_STD"),
    ("&ldquo;Funziona con i radiatori che ho già?&rdquo;","Temperatura massima di mandata dell&rsquo;unità contro il tipo di emettitore descritto dal cliente; passa a una persona quando la risposta è al limite.","product.max_flow_temp_c"),
    ("&ldquo;Rientra nel Conto Termico?&rdquo;","Classe ErP e valore SCOP dai documenti di certificazione nel DAM, inviati via email come PDF originale.","docs.erp_class &middot; docs.scop"),
    ("&ldquo;Se ordino oggi, quando arriva?&rdquo;","Disponibile-a-promettere nell&rsquo;ERP, più il lead time fornitore quando l&rsquo;articolo non è a magazzino.","erp.atp &middot; supplier.lead_days"),
    ("&ldquo;Dov&rsquo;è il resto del kit di installazione?&rdquo;","Eventi di tracking sull&rsquo;ordine padre, spedizioni parziali riconciliate in una risposta sola.","carrier.events &middot; order.shipments[]")],
  "workflows": [("Consulenza pre-vendita","Dimensionamento, compatibilità, cosa c&rsquo;è nella scatola. La chiamata che decide la vendita.","/it/casi-duso/consulenza-pre-vendita"),
                ("Preventivi automatici","Richieste di impianto raccolte con i campi che servono davvero a un preventivo.","/it/casi-duso/preventivi-automatici"),
                ("Dov&rsquo;è il mio ordine","Spedizioni parziali e kit di posa, riconciliati in una risposta parlata.","/it/casi-duso/dove-e-il-mio-ordine"),
                ("Riepilogo checkout via messaggio","Conferma di un ordine da quattro righe con la data di posa, prima dell&rsquo;addebito.","/it/casi-duso/riepilogo-checkout-via-messaggio")],
  "transcript_meta": "In entrata &middot; 2 min 41 s &middot; lingua: italiano &middot; esito: sopralluogo fissato",
  "transcript": [("caller","Buongiorno, guardavo il monosplit da 9 kW sul sito. Ho circa 120 metri quadri, tutti su un piano, fuori Milano. È quello giusto?"),
    ("agent","Controllo la tabella di dimensionamento. 120 metri quadri su un piano, zona climatica E - per il raffrescamento siamo intorno agli undici, dodici kilowatt, quindi il 9 kW ad agosto lavorerebbe sempre al massimo. Il 12 kW è la scelta più sicura. L&rsquo;altezza del soffitto è standard, sui 2,70?"),
    ("caller","Sì, standard. Niente di particolare."),
    ("agent","Allora il 12 kW. Una cosa da sapere prima di ordinare: serve una linea dedicata da sedici ampere. Se non è sicuro di averla, l&rsquo;installatore la verifica in sopralluogo."),
    ("caller","Ecco, l&rsquo;altra domanda era proprio questa: l&rsquo;installazione la fate voi o me la cerco io?"),
    ("agent","Sul suo CAP operano tre installatori certificati. La posa si preventiva a parte dopo il sopralluogo, e il sopralluogo è gratuito e dura una ventina di minuti."),
    ("caller","E per il Conto Termico rientra?"),
    ("agent","Questo modello è in classe ErP A+++ con SCOP 4,6, quindi sì. Le mando via email il PDF della certificazione e i due installatori più vicini. Le fisso il sopralluogo?"),
    ("caller","Sì, proceda pure.")],
  "data_h2": "I dati dietro una risposta sul clima",
  "data_copy": "Ogni risposta di questa pagina dipende da un campo che qualcuno deve mantenere. Dove il campo manca lo diciamo in chiamata e passiamo la mano - non lasciamo che l&rsquo;agente arrivi a un valore in kilowatt ragionandoci sopra.",
  "data_rows": [("Tabelle kW / BTU","Per modello, con le assunzioni dichiarate: superficie, altezza, classe di isolamento."),
    ("Zona climatica per CAP","Zone A - F, mappate sulla temperatura di progetto invernale."),
    ("Classe ErP, SCOP, SEER","Come documenti, non come testo di marketing - l&rsquo;agente invia il PDF che serve alla pratica."),
    ("Copertura installatori","Quali installatori certificati coprono quali CAP, e con che tempi di agenda."),
    ("Disponibile-a-promettere","Giacenza più ordini fornitore in arrivo, così i tempi detti al telefono sono quelli che l&rsquo;ERP mantiene.")],
  "proof": "Sabato risponde al telefono per ClimaConvenienza - pompe di calore, caldaie e climatizzazione, su Shopify.",
  "faq": [("Un agente vocale può davvero dimensionare una pompa di calore al telefono?","Legge la tua tabella di dimensionamento contro superficie, altezza e zona climatica del cliente, e segnala i casi che richiedono una persona: compatibilità emettitori al limite, alimentazione trifase, qualsiasi cosa non mappata. Non inventa un valore in kilowatt. Un dimensionamento che finisce in ordine va comunque confermato in sopralluogo, e il sopralluogo lo fissa l&rsquo;agente."),
    ("Funziona in italiano e in inglese sulla stessa linea?","Sì. L&rsquo;agente rileva la lingua del chiamante alla prima battuta e ci resta per tutta la chiamata, email di riepilogo compresa. Sabato nasce per i merchant europei, quindi il multilingua è il default, non un modulo aggiuntivo."),
    ("Cosa succede fuori orario?","L&rsquo;agente risponde, gestisce quello che può leggere dai tuoi sistemi - stato ordine, disponibilità, documenti - e fissa un richiamo con il team posa per tutto il resto. Le chiamate serali e del fine settimana sono quelle che i merchant del clima perdono più spesso."),
    ("In cosa è diverso da una chat sulla scheda prodotto?","Sabato risponde al telefono. In queste categorie il cliente ha già deciso che scrivere non basta: vuole descrivere casa sua a qualcuno. Un widget di chat quella chiamata non può prenderla, e una segreteria la perde."),
    ("Cosa serve dal nostro store Shopify per partire?","Accesso in lettura a ordini e prodotti, le tabelle di dimensionamento e i documenti di certificazione, e l&rsquo;elenco di copertura degli installatori. Quasi tutti hanno i primi due e tengono il terzo su un foglio di calcolo: va benissimo, lo mappiamo noi.")],
  "cta_h2": "Ascolta l&rsquo;agente su una chiamata di dimensionamento",
  "cta_sub": "Nella call di presentazione lo facciamo girare sul tuo catalogo - la tua tabella, i tuoi CAP, le tue domande.",
  "cta_hand": "venti minuti, senza slide"},

"ricambi-auto": {
  "en": "automotive-parts", "alias": ["Automotive e Ricambi", "Automotive &amp; Parts"],
  "label": "Automotive e Ricambi", "when": "before", "scene": "auto",
  "title": "Voice AI per E-Commerce di Ricambi Auto | Compatibilità | Sabato AI",
  "description": "Chi compra ricambi telefona per una domanda sola: è compatibile con la mia auto? Un agente vocale che risponde da targa, dati di compatibilità e codici sostitutivi.",
  "h1": "Ogni chiamata sui ricambi è la stessa domanda con un&rsquo;auto diversa.",
  "sub": "È compatibile con la mia? L&rsquo;agente di Sabato prende la targa o il telaio, controlla la tabella di compatibilità e risponde sì, no, oppure &ldquo;quel codice è stato sostituito - il ricambio attuale è questo&rdquo;.",
  "hand": "la compatibilità è tutta la conversazione",
  "call_q": "&ldquo;Ho una Golf del 2016, 2.0 TDI - questi dischi anteriori vanno bene?&rdquo;",
  "call_meta": [("Intento rilevato","Verifica compatibilità"),("Dati letti","Targa &middot; tabella compatibilità"),("Esito","Confermato + pastiglie")],
  "band_eyebrow": "Perché questa categoria telefona",
  "band_h2": "Un ricambio sbagliato è un reso, un rimontaggio e un cliente che il prossimo lo compra altrove.",
  "band_copy": ["Chi compra ricambi non sta guardando le vetrine. Ha un&rsquo;auto smontata, o un cliente che aspetta, e una domanda precisa: è compatibile. Se sbagli paghi il reso, il corriere e spesso una contestazione dell&rsquo;officina che il lavoro l&rsquo;aveva già iniziato.",
                "La scheda prodotto può ospitare la ricerca per targa, e dovrebbe farlo. Non può però rispondere a &ldquo;la mia è il restyling, cambia la pinza?&rdquo; - che è esattamente la chiamata che arriva."],
  "rank_head": "Di cosa parlano le chiamate in entrata",
  "rank": ["È compatibile con la mia auto (targa o telaio)","È la versione giusta - restyling, codice motore, allestimento","Il codice è stato sostituito, da cosa","Originale o aftermarket, e sono equivalenti","Dov&rsquo;è l&rsquo;ordine, ho l&rsquo;auto sul ponte"],
  "questions_h2": "Cinque domande che un centralino ricambi sente ogni giorno - e cosa deve esserci nei tuoi sistemi",
  "questions_intro": "La compatibilità è un problema di dati prima che di servizio. Ogni risposta qui si risolve su una tabella precisa, e dove la tabella è incompleta l&rsquo;agente passa la mano invece di tirare a indovinare: una compatibilità sbagliata detta con sicurezza è la risposta più costosa di questa categoria.",
  "questions": [
    ("&ldquo;Va bene per una Golf 2016 2.0 TDI?&rdquo;","Targa o numero di telaio decodificati nella versione esatta, poi incrociati con la tabella di compatibilità della famiglia di ricambi.","vehicle.by_vin &middot; fitment.k_type"),
    ("&ldquo;La mia è il restyling - cambia qualcosa?&rdquo;","Intervallo di data di costruzione sul record di compatibilità: è da lì che nasce la maggior parte degli ordini sbagliati.","fitment.build_from &middot; fitment.build_to"),
    ("&ldquo;Quel codice non lo trovo più.&rdquo;","Catena di sostituzione seguita fino al ricambio attuale, con il codice originale riportato nelle note d&rsquo;ordine per l&rsquo;officina.","part.superseded_by[]"),
    ("&ldquo;L&rsquo;aftermarket vale l&rsquo;originale?&rdquo;","Fascia del marchio e corrispondenza con i codici OE, dichiarata come equivalenza dai tuoi dati - non come opinione dell&rsquo;agente.","part.oe_refs[] &middot; brand.tier"),
    ("&ldquo;Mi serve domani, ho l&rsquo;auto sul ponte.&rdquo;","Giacenza per magazzino più l&rsquo;orario limite per la spedizione in giornata sul CAP del chiamante.","stock.by_wh &middot; carrier.cutoff")],
  "workflows": [("Consulenza pre-vendita","La chiamata sulla compatibilità. Quella che decide se l&rsquo;ordine è giusto.","/it/casi-duso/consulenza-pre-vendita"),
                ("Dov&rsquo;è il mio ordine","Un&rsquo;officina con l&rsquo;auto sul ponte chiede in modo diverso. Risposta dai tracking in tempo reale.","/it/casi-duso/dove-e-il-mio-ordine"),
                ("Gestione resi","Resi da ricambio sbagliato classificati per causa, così i dati di compatibilità si correggono invece di limitarsi a processare il reso.","/it/casi-duso/gestione-resi"),
                ("Riepilogo checkout via messaggio","Codice, veicolo e conferma di compatibilità per iscritto prima dell&rsquo;addebito.","/it/casi-duso/riepilogo-checkout-via-messaggio")],
  "transcript_meta": "In entrata &middot; 1 min 58 s &middot; lingua: italiano &middot; esito: ordine corretto",
  "transcript": [("caller","Buongiorno, cerco i dischi freno anteriori per una Golf del 2016, il 2.0 diesel."),
    ("agent","Se ha la targa glielo verifico esattamente."),
    ("caller","Sì, è una Golf 7, la targa ce l&rsquo;ho sul libretto, un attimo."),
    ("agent","Con calma. Intanto: è il modello base o la GTD?"),
    ("caller","Base. Targa FN471TK."),
    ("agent","Trovata - Golf 2.0 TDI, immatricolata marzo 2016, quindi post-restyling. Monta il disco autoventilante da 312 millimetri, non il 288 delle prime. Quelli che stava guardando sono i 288, quindi non andrebbero."),
    ("caller","Meno male che ho chiamato."),
    ("agent","La coppia da 312 è disponibile nel magazzino di Bologna, l&rsquo;orario limite per la consegna domani è le sedici. Di solito si prendono anche le pastiglie: stesso asse, stesso intervento. Gliele aggiungo?"),
    ("caller","Sì, entrambe.")],
  "data_h2": "I dati dietro una risposta di compatibilità",
  "data_copy": "I dati di compatibilità invecchiano male. I costruttori rivedono, sostituiscono e ri-referenziano di continuo, e una tabella corretta due anni fa oggi produce risposte sbagliate in silenzio. Li verifichiamo prima del pilota.",
  "data_rows": [("Decodifica veicolo","Targa o telaio fino alla versione esatta: codice motore, data di costruzione, allestimento."),
    ("Tabella di compatibilità","Famiglia di ricambi per versione, con gli intervalli di data - il campo che manca più spesso."),
    ("Catene di sostituzione","Dal codice vecchio a quello attuale, così un riferimento fuori produzione porta comunque a una vendita."),
    ("Riferimenti incrociati OE","Quali codici aftermarket corrispondono a quali OE, e in che fascia di marchio."),
    ("Giacenza per magazzino","Più gli orari limite dei corrieri, perché per un&rsquo;officina la consegna in giornata è tutta la domanda.")],
  "proof": None,
  "faq": [("Un agente vocale può confermare la compatibilità al telefono?","Solo quanto lo permette la tua tabella. Con targa o telaio decodifica la versione e verifica la famiglia di ricambi, intervalli di data compresi. Dove non c&rsquo;è un record per quella versione lo dice e passa la mano: non deduce la compatibilità da un modello simile."),
    ("E i clienti professionali che chiamano ogni giorno?","Sono quelli che ne beneficiano di più, perché la chiamata è corta e ripetitiva: codice, veicolo, giacenza, orario limite. L&rsquo;agente riconosce l&rsquo;account dal numero e salta le parti che a un abituale non servono."),
    ("Se il cliente non ha il numero di telaio?","Chiede prima la targa, e in mancanza ripiega su marca, modello, anno e motore, segnalando che la risposta è meno certa di una verifica da telaio. Quel distinguo viene detto, non nascosto."),
    ("Funziona fuori orario e nel fine settimana?","Sì, e in questa categoria conta più che altrove: molti acquisti di ricambi avvengono di sabato, con l&rsquo;auto già smontata."),
    ("Cosa serve per partire?","Accesso in lettura a prodotti e ordini, le tabelle di compatibilità e sostituzione, e la giacenza per magazzino con gli orari limite. Se la compatibilità sta in un feed fornitore invece che a catalogo, leggiamo il feed.")],
  "cta_h2": "Ascolta l&rsquo;agente su una chiamata di compatibilità",
  "cta_sub": "Porta una targa e un codice ricambio alla call. Lo facciamo girare sui tuoi dati, dal vivo.",
  "cta_hand": "porta una targa, proviamo"},

"elettronica": {
  "en": "electronics-tech", "alias": ["Elettronica e Tech", "Electronics &amp; Tech"],
  "label": "Elettronica e Tech", "when": "before", "scene": "electronics",
  "title": "Voice AI per E-Commerce di Elettronica | Compatibilità | Sabato AI",
  "description": "Chi compra elettronica chiama per compatibilità e differenze di specifica. Un agente vocale che risponde dalla tua matrice attributi e gestisce la coda resi dietro.",
  "h1": "&ldquo;Funziona con quello che ho già?&rdquo;",
  "sub": "Chi compra elettronica sta confrontando due modelli, e uno dei due ce l&rsquo;ha già in casa. L&rsquo;agente di Sabato legge la matrice degli attributi, dice qual è la differenza reale, e ferma l&rsquo;ordine sbagliato prima che parta.",
  "hand": "domande di specifica, risposte dai dati di specifica",
  "call_q": "&ldquo;Questa dock funziona con un MacBook Pro 2021 e due monitor 4K?&rdquo;",
  "call_meta": [("Intento rilevato","Verifica compatibilità"),("Dati letti","Matrice attributi &middot; porte"),("Esito","Modello cambiato, ordine chiuso")],
  "band_eyebrow": "Perché questa categoria telefona",
  "band_h2": "La specifica è sulla pagina. La risposta no.",
  "band_copy": ["Le schede prodotto dell&rsquo;elettronica sono fittissime di attributi e continuano a non rispondere all&rsquo;unica domanda che conta: funziona con quello che ho. Il cliente legge &ldquo;HDMI 2.0&rdquo; e continua a non sapere se il suo monitor andrà a 120 Hz.",
                "Quindi chiama - e il costo di non rispondere non è una vendita persa, è un pezzo venduto e reso, aperto, non più vendibile come nuovo, con il corriere pagato due volte."],
  "rank_head": "Di cosa parlano le chiamate in entrata",
  "rank": ["È compatibile con quello che ho già","Qual è la differenza vera fra questi due modelli","Sta per uscire la versione nuova","Garanzia e cosa la fa decadere","Dov&rsquo;è l&rsquo;ordine / posso rendere un prodotto aperto"],
  "questions_h2": "Cinque domande che un centralino di elettronica sente ogni giorno - e cosa deve esserci nei tuoi sistemi",
  "questions_intro": "Questa categoria punisce le risposte vaghe. Ogni risposta si risolve su un attributo strutturato, e dove l&rsquo;attributo manca su un vecchio codice l&rsquo;agente lo dice, invece di rileggere il testo di marketing.",
  "questions": [
    ("&ldquo;Questa dock regge due monitor 4K a 60 Hz?&rdquo;","Specifica delle porte e attributi di banda sul prodotto, verificati contro la configurazione descritta dal cliente.","attr.ports[] &middot; attr.max_resolution"),
    ("&ldquo;Che differenza c&rsquo;è davvero fra la Pro e la standard?&rdquo;","Differenza attributo per attributo fra i due codici, detta come sole differenze - non come lettura di entrambe le schede.","sku.diff(a, b)"),
    ("&ldquo;Sta per uscire la nuova? Non voglio comprare la vecchia.&rdquo;","Stato di ciclo di vita del prodotto ed eventuale successore annunciato, dove lo tieni. Dove non c&rsquo;è, l&rsquo;agente dice che non lo sa.","product.lifecycle_state"),
    ("&ldquo;Se lo apro e non va bene, posso comunque renderlo?&rdquo;","La tua policy di reso per l&rsquo;elettronica aperta, per canale - la risposta che più spesso non coincide con quello che lascia intendere il sito.","returns.policy.opened"),
    ("&ldquo;La garanzia è vostra o del produttore?&rdquo;","Durata e canale di assistenza sul prodotto, incluso a chi si rivolge davvero il cliente il secondo anno.","attr.warranty_months &middot; brand.claim_route")],
  "workflows": [("Consulenza pre-vendita","La chiamata sulla compatibilità. Evita il reso da confezione aperta.","/it/casi-duso/consulenza-pre-vendita"),
                ("Gestione resi","Elettronica aperta, verificata contro la policy prima di emettere un RMA.","/it/casi-duso/gestione-resi"),
                ("Dov&rsquo;è il mio ordine","Colli di valore alto: il &ldquo;dov&rsquo;è&rdquo; pesa più che altrove.","/it/casi-duso/dove-e-il-mio-ordine"),
                ("Notifica ritorno in stock","Lanci e allocazioni, dove la chiamata di riassortimento vale la pena.","/it/casi-duso/notifica-ritorno-in-stock")],
  "transcript_meta": "In entrata &middot; 2 min 06 s &middot; lingua: italiano &middot; esito: passato al modello corretto",
  "transcript": [("caller","Sto guardando la dock USB-C, quella da novantanove. Ho un MacBook Pro del 2021 e due monitor 4K."),
    ("agent","Quella dock ha due uscite HDMI 2.0. Su un MacBook Pro 2021 avrebbe entrambi gli schermi in 4K, ma il secondo limitato a 30 hertz - cosa che sulla scrivania si nota subito."),
    ("caller","Mi darebbe fastidio, sì."),
    ("agent","Allora è la versione Thunderbolt. Entrambi gli schermi 4K a 60, e alimenta il portatile a novantasei watt quindi si toglie un cavo. Costa centosettanta invece di novantanove."),
    ("caller","Serve un alimentatore a parte?"),
    ("agent","È incluso. E siccome è quella più costosa le dico anche la parte sui resi: aperta va bene entro trenta giorni, purché torni tutto insieme."),
    ("caller","D&rsquo;accordo. Prendo la Thunderbolt.")],
  "data_h2": "I dati dietro una risposta di compatibilità",
  "data_copy": "Questa categoria ha più dati prodotto di ogni altra e meno dati strutturati. Una compatibilità scritta a parole dentro un PDF non è leggibile da nulla - né da un agente, né dai motori di ricerca AI che citano la tua pagina.",
  "data_rows": [("Attributi strutturati","Porte, banda, potenza, risoluzione - come campi, non come frasi nella descrizione."),
    ("Matrice di compatibilità","Quali codici funzionano con quali dispositivi e a che livello, avvertenze comprese."),
    ("Stato di ciclo di vita","Attuale, fine vita, successore annunciato. Evita di vendere il modello uscente."),
    ("Policy di reso su prodotto aperto","Per canale e categoria: è qui che risposta telefonica e sito divergono più spesso."),
    ("Garanzia e canale di assistenza","Durata, e a chi si rivolge davvero il cliente il secondo anno.")],
  "proof": None,
  "faq": [("Risponde davvero bene alle domande di compatibilità?","Dove tieni attributi strutturati sì: li legge contro quello che il cliente descrive. Dove la compatibilità esiste solo come testo dentro un PDF non può, e passa la mano invece di parafrasare. È un divario che conviene conoscere prima di un pilota, non dopo."),
    ("Proporrà sempre il modello più caro?","Propone il modello che risponde alla domanda, che a volte costa di più e a volte di meno. Un agente che fa sempre upsell smette di essere creduto, e qui il cliente ti sta confrontando con una scheda tecnica che ha già aperta."),
    ("E la coda resi dopo la vendita?","È il secondo workflow di questa pagina, non a caso. I resi di elettronica aperta costano, e l&rsquo;agente li classifica contro la policy reale invece di quella che il sito lascia intendere."),
    ("Regge un cliente tecnico?","Ragionevolmente: resta sui dettagli e passa la mano quando la domanda supera i tuoi dati. Non bluffa, che è il modo di fallire che un cliente tecnico riconosce più in fretta."),
    ("Cosa serve per partire?","Accesso in lettura a prodotti e ordini, i tuoi attributi, e la policy di reso sull&rsquo;aperto. Se gli attributi sono scarsi sui codici più vecchi te lo diciamo prima del lancio.")],
  "cta_h2": "Ascolta l&rsquo;agente su una chiamata di compatibilità",
  "cta_sub": "Porta alla call la tua domanda di specifica più difficile. La facciamo girare sui tuoi attributi.",
  "cta_hand": "porta la domanda più difficile"},

"arredamento": {
  "en": "furniture-home", "alias": ["Arredamento e Casa", "Furniture &amp; Home"],
  "label": "Arredamento e Casa", "when": "before", "scene": "furniture",
  "title": "Voice AI per E-Commerce di Arredamento | Misure e Consegna | Sabato AI",
  "description": "Chi compra arredamento chiama per misure, accessi e finestre di consegna. Un agente vocale che risponde dai tuoi dati prodotto e dal calendario consegne, 24/7.",
  "h1": "Nella stanza ci sta. Il problema sono le scale.",
  "sub": "Chi compra un divano la nicchia l&rsquo;ha già misurata. Quello che non sa è la curva del pianerottolo, la finestra di consegna, e se il vecchio divano lo portate via. L&rsquo;agente di Sabato risponde a tutte e tre.",
  "hand": "la vendita si blocca sull&rsquo;accesso, non sul gusto",
  "call_q": "&ldquo;Il tre posti sale da una scala a chiocciola? E ritirate il vecchio?&rdquo;",
  "call_meta": [("Intento rilevato","Accesso + consegna"),("Dati letti","Misure imballo &middot; calendario"),("Esito","Slot fissato, ritiro incluso")],
  "band_eyebrow": "Perché questa categoria telefona",
  "band_h2": "Un divano è una decisione di logistica travestita da acquisto.",
  "band_copy": ["Sul divano il cliente ha già deciso. Quello che blocca l&rsquo;ordine è la porta, l&rsquo;ascensore, il martedì in cui è davvero in casa, e se il vecchio viene portato via. Niente di tutto questo sta sulla scheda prodotto, e tutto è conoscibile.",
                "Sbagliare qui costa in un modo che nel tessile non esiste: una squadra da due persone, uno slot sprecato, e un mobile che torna a magazzino come pezzo unico."],
  "rank_head": "Di cosa parlano le chiamate in entrata",
  "rank": ["Misure, e se passa","Slot di consegna, e se posso cambiarlo","Montaggio, e se ritirate il vecchio","Tempi su un pezzo su ordinazione","Tessuto, finitura e se posso avere un campione"],
  "questions_h2": "Cinque domande che un centralino di arredamento sente ogni giorno - e cosa deve esserci nei tuoi sistemi",
  "questions_intro": "Questa categoria ha bisogno di due cose che quasi nessun catalogo tiene bene: le misure da imballo distinte da quelle da montato, e un calendario consegne che il telefono possa davvero leggere.",
  "questions": [
    ("&ldquo;Sale da una scala a chiocciola?&rdquo;","Misure da imballo - non da montato - e se il pezzo si separa, che è il dato che risolve quasi tutte le domande di accesso.","product.packed_dims &middot; product.modular"),
    ("&ldquo;Quando consegnate, e posso scegliere il giorno?&rdquo;","Calendario consegne con due operatori sul CAP del cliente, prenotato in chiamata invece che confermato dopo per email.","delivery.slots(postcode)"),
    ("&ldquo;Ritirate il divano vecchio?&rdquo;","Disponibilità del servizio di ritiro per zona e relativo costo, aggiunto all&rsquo;ordine mentre il cliente è in linea.","service.removal.by_area"),
    ("&ldquo;Dice su ordinazione - quanto davvero?&rdquo;","Tempo di produzione sulla combinazione specifica di tessuto e struttura, non il dato medio di catalogo.","variant.production_days"),
    ("&ldquo;Posso vedere il tessuto prima di decidere?&rdquo;","Disponibilità del campione per quel tessuto, spedito durante la chiamata - la cosa più economica che puoi fare per evitare un reso da colore.","swatch.available &middot; swatch.sku")],
  "workflows": [("Consulenza pre-vendita","Misure, accesso e finiture. Le domande che decidono un ordine da quattro cifre.","/it/casi-duso/consulenza-pre-vendita"),
                ("Dov&rsquo;è il mio ordine","Tempi lunghi significano più chiamate di stato per ordine che in qualsiasi altra categoria.","/it/casi-duso/dove-e-il-mio-ordine"),
                ("Feedback post-consegna","Danni e problemi di montaggio intercettati quando sono ancora rimediabili.","/it/casi-duso/feedback-post-consegna"),
                ("Preventivi automatici","Richieste multi-pezzo e contract raccolte bene già la prima volta.","/it/casi-duso/preventivi-automatici")],
  "transcript_meta": "In entrata &middot; 2 min 22 s &middot; lingua: italiano &middot; esito: slot fissato con ritiro",
  "transcript": [("caller","Vorrei il tre posti grigio, ma sono al primo piano e la scala fa la curva."),
    ("agent","Le controllo la misura da imballo invece che da montato - è quella che conta. Arriva in due colli, il più grande è 205 per 96 per 82 centimetri, e i piedini sono smontati."),
    ("caller","Due colli è meglio di quanto pensassi."),
    ("agent","Su questo modello di solito lo è. Se la curva del pianerottolo è larga almeno un metro sale senza problemi. Sa più o meno quanto è?"),
    ("caller","Più o meno sì. E per la consegna?"),
    ("agent","Consegna con due operatori sul suo CAP: il primo disponibile è giovedì quattordici, poi il martedì successivo. Entrambi in giornata, con finestra di due ore comunicata via SMS la sera prima."),
    ("caller","Martedì. E il divano vecchio lo portate via?"),
    ("agent","Sì - trentacinque euro nella sua zona, e lo ritira la stessa squadra nello stesso passaggio. Lo aggiungo e le fisso il martedì.")],
  "data_h2": "I dati dietro una risposta sull&rsquo;arredamento",
  "data_copy": "I due campi che contano di più in questa categoria sono i due che mancano più spesso: le misure da imballo, e un calendario consegne leggibile da qualcosa che non sia una persona.",
  "data_rows": [("Misure imballo e montato","Entrambe, come campi distinti. Le domande di accesso si risolvono con le prime e quasi mai con le seconde."),
    ("Calendario consegne per CAP","Slot reali per la consegna con due operatori, prenotabili in chiamata."),
    ("Servizi di ritiro e montaggio","Disponibilità per zona e prezzo, per aggiungerli mentre il cliente decide."),
    ("Tempi di produzione","Per combinazione di tessuto e struttura, non una media di catalogo."),
    ("Campionario tessuti","Quali tessuti si possono campionare e in quanto tempo: un campione costa meno di un divano reso.")],
  "proof": None,
  "faq": [("Può davvero dire se un mobile sale dalle scale?","Dà al cliente le misure da imballo e dice se il pezzo si separa, che è ciò su cui la domanda si decide davvero. Non fa un sopralluogo: consegna i numeri che servono e segnala quando la risposta è al limite."),
    ("Può prenotare uno slot di consegna in chiamata?","Sì, dove il calendario è leggibile via API. È l&rsquo;integrazione a più alto valore di questa categoria, perché uno slot fissato in chiamata è uno slot che non diventa tre email."),
    ("E i tempi sui pezzi su ordinazione?","Legge il tempo di produzione della combinazione specifica che il cliente sta chiedendo. I tempi medi di catalogo sono l&rsquo;origine di gran parte delle chiamate di stato nell&rsquo;arredamento."),
    ("Gestisce anche i problemi dopo la consegna?","Danni e montaggio vengono passati a una persona con il contesto dell&rsquo;ordine. L&rsquo;agente serve a intercettarli presto, non a chiudere una contestazione."),
    ("Cosa serve per partire?","Prodotti con le misure da imballo, il calendario consegne e l&rsquo;elenco servizi di ritiro e montaggio. Quasi tutti tengono il terzo su un foglio di calcolo, e va bene.")],
  "cta_h2": "Ascolta l&rsquo;agente su una chiamata di consegna e accesso",
  "cta_sub": "Nella call lo facciamo girare sulle tue misure e sul tuo calendario consegne.",
  "cta_hand": "venti minuti, senza slide"},

"industria-b2b": {
  "en": "industrial-b2b", "alias": ["Industria e B2B", "Industrial &amp; B2B"],
  "label": "Industria e B2B", "when": "before", "scene": "industrial",
  "title": "Voice AI per E-Commerce Industriale e B2B | Preventivi | Sabato AI",
  "description": "I buyer industriali chiamano per conferme di capitolato, prezzi di contratto e tempi. Un agente vocale che legge l'ERP e raccoglie le richieste di preventivo.",
  "h1": "L&rsquo;ordine è piccolo. Le conseguenze di sbagliarlo no.",
  "sub": "I buyer industriali chiamano per confermare una tolleranza, una certificazione, un prezzo di contratto o un tempo di consegna prima di fermare una linea. L&rsquo;agente di Sabato risponde dall&rsquo;ERP e raccoglie la richiesta con i campi che servono davvero.",
  "hand": "prima il capitolato, poi il prezzo",
  "call_q": "&ldquo;La versione in 316 ha il 3.1, e sul mio contratto quanto viene a 200 pezzi?&rdquo;",
  "call_meta": [("Intento rilevato","Capitolato + prezzo contratto"),("Dati letti","Certificati &middot; listino account"),("Esito","Preventivo emesso in chiamata")],
  "band_eyebrow": "Perché questa categoria telefona",
  "band_h2": "Nessuno sceglie una vite da una fotografia.",
  "band_copy": ["L&rsquo;acquisto industriale è verifica. Il buyer sa cosa gli serve, e chiama per confermare la classe, la certificazione, la tolleranza e il prezzo sul suo account prima di impegnarsi - perché il costo di un pezzo sbagliato è una linea ferma, non un reso.",
                "Sono chiamate corte, ripetitive e molto qualificate. Sono anche quelle che finiscono in segreteria alle sei di sera, che è esattamente quando la manutenzione scopre cosa le manca."],
  "rank_head": "Di cosa parlano le chiamate in entrata",
  "rank": ["Conferma di capitolato e materiale","Il mio prezzo su questa quantità","Certificazioni e documentazione","Tempi e se è a magazzino","Dov&rsquo;è l&rsquo;ordine, abbiamo la linea ferma"],
  "questions_h2": "Cinque domande che un centralino industriale sente ogni giorno - e cosa deve esserci nei tuoi sistemi",
  "questions_intro": "Il prezzo per account rende questa categoria diversa: l&rsquo;agente deve riconoscere chi sta chiamando prima di poter rispondere sul prezzo. Tutto il resto si risolve sull&rsquo;ERP.",
  "questions": [
    ("&ldquo;È la classe 316, e con che tolleranza?&rdquo;","Classe del materiale e tolleranza come attributi strutturati, con la norma di riferimento.","attr.material_grade &middot; attr.tolerance_class"),
    ("&ldquo;Su duecento pezzi che prezzo faccio?&rdquo;","Account riconosciuto dal numero, poi il suo listino di contratto a quello scaglione - non il prezzo di listino pubblico.","account.by_phone &middot; pricelist.break(qty)"),
    ("&ldquo;Mi mandate il 3.1?&rdquo;","Il certificato di quel lotto, inviato via email durante la chiamata come documento originale.","docs.cert_3_1 &middot; batch.id"),
    ("&ldquo;È a magazzino o è un tempo di consegna?&rdquo;","Giacenza libera al netto degli impegni, più il tempo fornitore quando l&rsquo;articolo non è tenuto.","erp.free_stock &middot; supplier.lead_days"),
    ("&ldquo;Abbiamo la linea ferma - cosa arriva domani?&rdquo;","Giacenza libera su tutti i magazzini più le opzioni di spedizione urgente disponibili su quell&rsquo;account.","stock.free_by_wh &middot; expedite.options")],
  "workflows": [("Preventivi automatici","Il workflow di volume qui. Richieste raccolte con i campi che un preventivo richiede davvero.","/it/casi-duso/preventivi-automatici"),
                ("Consulenza pre-vendita","Conferma di capitolato e certificazioni prima dell&rsquo;impegno d&rsquo;ordine.","/it/casi-duso/consulenza-pre-vendita"),
                ("Dov&rsquo;è il mio ordine","Una linea di produzione ferma chiede in modo diverso, e vuole una risposta subito.","/it/casi-duso/dove-e-il-mio-ordine"),
                ("Riepilogo checkout via messaggio","Codice, classe, certificazione e prezzo confermati per iscritto su un ordine d&rsquo;acquisto.","/it/casi-duso/riepilogo-checkout-via-messaggio")],
  "transcript_meta": "In entrata &middot; 1 min 44 s &middot; lingua: italiano &middot; esito: preventivo emesso in chiamata",
  "transcript": [("caller","Buongiorno, mi servono le viti a brugola M10, quelle inox, in 316 non in 304."),
    ("agent","Dal numero risulta Meccanica Ferrari, confermo?"),
    ("caller","Sì, siamo noi."),
    ("agent","Allora sul vostro account la M10 per 40 in 316 è a un euro e diciotto fino a cento pezzi, e novantaquattro centesimi da duecento. Entrambe a magazzino a Bologna."),
    ("caller","Duecento allora. Vengono con il 3.1?"),
    ("agent","Sì - le mando il certificato del lotto corrente appena chiudiamo, insieme al preventivo."),
    ("caller","E se ordino stamattina?"),
    ("agent","L&rsquo;orario limite è le quattordici per la consegna domani sul vostro CAP, quindi domani entro mezzogiorno. Le preparo il preventivo con il vostro riferimento d&rsquo;ordine abituale?"),
    ("caller","Sì, faccia pure.")],
  "data_h2": "I dati dietro una risposta industriale",
  "data_copy": "Il requisito che distingue questa categoria è il riconoscimento dell&rsquo;account. Un agente che non sa chi sta chiamando non può rispondere sul prezzo, e il prezzo è dentro quasi tutte queste chiamate.",
  "data_rows": [("Riconoscimento account","Dal numero all&rsquo;anagrafica, così prezzi e condizioni sono disponibili dalla prima frase."),
    ("Listini di contratto","Per account, con gli scaglioni. Il prezzo di listino è la risposta sbagliata a un cliente professionale."),
    ("Attributi di materiale e tolleranza","Strutturati, con la norma di certificazione."),
    ("Documenti di certificazione","Per lotto, recuperabili e inviabili durante la chiamata."),
    ("Giacenza libera al netto degli impegni","Non la giacenza lorda: il numero che l&rsquo;ERP manterrà davvero su un ordine.")],
  "proof": None,
  "faq": [("Può fare prezzi di contratto ai clienti professionali?","Dove riesce a identificare l&rsquo;account - di norma dal numero chiamante - legge il listino di quell&rsquo;account, scaglioni compresi. Chi non viene riconosciuto riceve il prezzo di listino e la proposta di un richiamo, non una stima inventata."),
    ("Può inviare i certificati durante la chiamata?","Sì, dove i documenti sono archiviati per lotto o per prodotto e raggiungibili. Mandare il certificato durante la chiamata elimina una delle attività di follow-up più frequenti della categoria."),
    ("Sostituisce il nostro ufficio commerciale interno?","No. Prende le chiamate ripetitive di verifica - capitolato, prezzo, giacenza, tempi - così l&rsquo;ufficio segue i pezzi speciali, le escalation tecniche e i clienti che vogliono una relazione. L&rsquo;agente passa la mano con tutto il contesto."),
    ("E le chiamate fuori orario dalla manutenzione?","È lì che sta buona parte del valore. I guasti non rispettano gli orari, e sapere alle sette di sera se un pezzo c&rsquo;è o non c&rsquo;è è spesso la differenza fra il tuo ordine e quello di un concorrente."),
    ("Cosa serve per partire?","Accesso in lettura all&rsquo;ERP per giacenze e prezzi, la corrispondenza numero-account, e i documenti di certificazione. La corrispondenza account è quella che quasi tutti devono ancora costruire.")],
  "cta_h2": "Ascolta l&rsquo;agente su una chiamata di capitolato",
  "cta_sub": "Porta un codice vero e un account vero alla call. Lo facciamo girare sui tuoi prezzi e sulle tue giacenze.",
  "cta_hand": "porta un codice vero"},

"giardino-outdoor": {
  "en": "outdoor-garden", "alias": ["Outdoor e Giardino", "Outdoor &amp; Garden"],
  "label": "Outdoor e Giardino", "when": "mixed", "scene": "outdoor",
  "title": "Voice AI per E-Commerce Giardino e Outdoor | Picchi Stagionali | Sabato AI",
  "description": "Il giardinaggio ha il picco stagionale di chiamate più netto dell'e-commerce. Un agente vocale che lo assorbe: dimensionamento, ricambi, riassortimenti e consegne.",
  "h1": "Il tuo volume di chiamate è una previsione meteo.",
  "sub": "La domanda arriva in una manciata di weekend caldi e sparisce. L&rsquo;agente di Sabato assorbe il picco senza un&rsquo;assunzione stagionale, gestisce le chiamate su ricambi e dimensionamento, e richiama chi voleva la cosa esaurita.",
  "hand": "il problema è il picco, non la media",
  "call_q": "&ldquo;Che rasaerba per 800 metri quadri, e il trattorino è tornato disponibile?&rdquo;",
  "call_meta": [("Intento rilevato","Dimensionamento + riassortimento"),("Dati letti","Larghezza taglio &middot; ordine fornitore"),("Esito","Richiamo fissato")],
  "band_eyebrow": "Perché questa categoria telefona",
  "band_h2": "Dodici settimane di domanda, e un centralino dimensionato per cinquantadue.",
  "band_copy": ["Il giardinaggio concentra quasi tutto l&rsquo;anno in una stagione corta, e le chiamate si concentrano ancora di più: il primo sabato caldo produce un volume che nessuna linea a organico fisso regge, e le chiamate perse in un picco sono quelle di chi era pronto a spendere.",
                "Il resto dell&rsquo;anno la stessa linea gestisce ricambi: un codice preso da una macchina comprata quattro stagioni fa, che è una ricerca, non una conversazione."],
  "rank_head": "Di cosa parlano le chiamate in entrata",
  "rank": ["Che misura o modello per il mio terreno","È tornato disponibile, e quando","Ricambio per una macchina che ho già","Consegna prima del weekend","Montaggio, tagliando e rimessaggio invernale"],
  "questions_h2": "Cinque domande che un centralino del giardinaggio sente ogni giorno - e cosa deve esserci nei tuoi sistemi",
  "questions_intro": "Due lavori molto diversi condividono una linea: le chiamate stagionali di dimensionamento da nuovi clienti, e le ricerche di ricambi da chi la macchina ce l&rsquo;ha già. I dati dietro sono diversi, ed entrambi sono rispondibili.",
  "questions": [
    ("&ldquo;Che rasaerba per ottocento metri quadri?&rdquo;","Larghezza di taglio e superficie consigliata sul prodotto, contro l&rsquo;area e il terreno descritti dal cliente.","attr.cutting_width_cm &middot; attr.plot_max_m2"),
    ("&ldquo;Quando torna disponibile?&rdquo;","Data dell&rsquo;ordine fornitore in arrivo confrontata con quanta stagione resta - un riassortimento che atterra a settembre è una risposta diversa da uno che atterra a maggio.","po.expected_at &middot; season.cutoff"),
    ("&ldquo;Mi serve la lama per un modello del 2021.&rdquo;","Compatibilità ricambi per modello e anno macchina, codici sostitutivi compresi.","spares.by_model(year) &middot; part.superseded_by[]"),
    ("&ldquo;Arriva prima del weekend?&rdquo;","Orario limite del corriere sul CAP del cliente - la domanda che decide l&rsquo;ordine in una categoria mossa da due giorni di sole.","carrier.cutoff &middot; stock.by_wh"),
    ("&ldquo;Ha bisogno di tagliando, e lo fate voi?&rdquo;","Intervallo di manutenzione sul prodotto e se offri il servizio, così la risposta è una prenotazione e non un forse.","attr.service_interval &middot; service.available")],
  "workflows": [("Consulenza pre-vendita","Dimensionamento sul terreno. La chiamata stagionale che converte.","/it/casi-duso/consulenza-pre-vendita"),
                ("Notifica ritorno in stock","Articoli di stagione esauriti, richiamati il giorno in cui rientrano.","/it/casi-duso/notifica-ritorno-in-stock"),
                ("Dov&rsquo;è il mio ordine","Volume di picco gestito senza assunzioni stagionali.","/it/casi-duso/dove-e-il-mio-ordine"),
                ("Gestione resi","Resi di fine stagione verificati contro la policy.","/it/casi-duso/gestione-resi")],
  "transcript_meta": "In entrata &middot; 1 min 49 s &middot; lingua: italiano &middot; esito: richiamo per riassortimento",
  "transcript": [("caller","Cerco un rasaerba per circa ottocento metri quadri, e dietro c&rsquo;è una pendenza."),
    ("agent","Con ottocento metri e una pendenza guarderei i modelli semoventi più che quelli a spinta - il taglio da 46 centimetri è quello che prendono quasi tutti per questa superficie."),
    ("caller","In realtà stavo guardando il trattorino, ma dice esaurito."),
    ("agent","Lo è, e non le racconto storie. C&rsquo;è una consegna prevista per il diciotto, quindi circa due settimane. Se vuole la richiamo la mattina in cui arriva e glielo tengo."),
    ("caller","Sì, faccia così. Nel frattempo il 46 farebbe il lavoro?"),
    ("agent","Lo farebbe senza problemi. E se lo vuole per questo weekend, l&rsquo;orario limite per la consegna di venerdì sul suo CAP è mercoledì alle quattordici."),
    ("caller","Ci penso. Il richiamo per il trattorino però me lo fissi."),
    ("agent","Fissato per il diciotto. Le mando anche il link del 46 via SMS, casomai il tempo cambiasse prima.")],
  "data_h2": "I dati dietro una risposta sul giardinaggio",
  "data_copy": "La forma stagionale è tutto il problema. Qui la concorrenza di chiamate conta più che in ogni altra categoria di questa lista: l&rsquo;agente prende tutte le chiamate insieme invece di metterle in coda, che è esattamente ciò che serve un sabato di picco.",
  "data_rows": [("Attributi di dimensionamento","Larghezza di taglio, superficie, potenza - come campi, così una superficie porta a un modello."),
    ("Ordini fornitore in arrivo","Date attese per variante, così una promessa di riassortimento è una data e non un&rsquo;alzata di spalle."),
    ("Compatibilità ricambi","Per modello e anno macchina, seguendo i codici sostitutivi."),
    ("Orari limite dei corrieri per CAP","In una categoria mossa dal meteo, &ldquo;prima del weekend&rdquo; è la decisione d&rsquo;acquisto."),
    ("Disponibilità assistenza","Intervalli e se fai manutenzione, così la risposta è una prenotazione.")],
  "proof": None,
  "faq": [("Cosa succede nel picco di stagione?","La concorrenza è il punto: l&rsquo;agente risponde a tutte le chiamate contemporaneamente invece di metterle in coda. I sabati di picco sono quando le chiamate perse esplodono, e in questa categoria chi rinuncia era pronto a spendere."),
    ("Gestisce le ricerche di ricambi per macchine vecchie?","Dove tieni la compatibilità per modello e anno sì, codici sostitutivi compresi. È la metà fuori stagione del lavoro di questa linea, ed è quasi tutta ricerca."),
    ("Ha senso se siamo carichi solo tre mesi l&rsquo;anno?","È la domanda onesta per questa categoria. Un livello vocale non ha tempi di assunzione stagionale né costi di formazione, ed è questo che rende gestibile una stagione corta - ma se il tuo picco è piccolo te lo diciamo nella call invece di vendertelo."),
    ("Può richiamare le persone quando la merce rientra?","Sì, e nel giardinaggio vale più di un&rsquo;email, perché la domanda di stagione ha una scadenza. L&rsquo;agente chiama, conferma e prende l&rsquo;ordine nella stessa chiamata."),
    ("Cosa serve per partire?","Prodotti con gli attributi di dimensionamento, le date degli ordini fornitore, la compatibilità ricambi e gli orari limite dei corrieri. Di solito è il dato ricambi quello da sistemare.")],
  "cta_h2": "Ascolta l&rsquo;agente su una chiamata di sabato di picco",
  "cta_sub": "Nella call lo facciamo girare sul tuo catalogo e sulle tue date di riassortimento - meglio prima che inizi la stagione.",
  "cta_hand": "prima della stagione, non durante"},

"moda-abbigliamento": {
  "en": "fashion-apparel", "alias": ["Fashion e Abbigliamento", "Fashion &amp; Apparel"],
  "label": "Fashion e Abbigliamento", "when": "after", "scene": "fashion",
  "title": "Voice AI per E-Commerce Moda e Abbigliamento | Sabato AI",
  "description": "Chi compra moda quasi mai telefona prima: telefona dopo. Un agente vocale che gestisce stato ordine, cambi taglia e riassortimenti dai dati d'ordine in tempo reale.",
  "h1": "Chi compra moda non telefona prima. Telefona dopo.",
  "sub": "Nessuno chiama per una t-shirt. Chiamano perché il pacco è in ritardo, la taglia era sbagliata, o il capo che volevano è tornato disponibile. Quella coda è post-acquisto, è stagionale, ed è quella che salta.",
  "hand": "qui la chiamata è il dopo, non la vendita",
  "call_q": "&ldquo;L&rsquo;ordine doveva arrivare martedì e il tracking è fermo da venerdì.&rdquo;",
  "call_meta": [("Intento rilevato","Stato ordine &middot; ritardo"),("Dati letti","Eventi corriere &middot; ordine 48213"),("Esito","Risposto, cambio proposto")],
  "band_eyebrow": "Perché questa categoria telefona",
  "band_h2": "La chiamata arriva dopo che i soldi si sono mossi, ed è per questo che costa più di quanto sembri.",
  "band_copy": ["Chi compra moda sceglie una giacca senza parlare con nessuno. La scheda prodotto fa il suo lavoro. Poi il pacco è in ritardo, o la 46 veste come una 42, e lo stesso cliente vuole una persona - subito, e di solito in una settimana di picco in cui la coda è già al peggio.",
                "Questo è lavoro di deflection e di retention, non di conversione. Lo diciamo chiaramente: su una t-shirt da 40 euro non c&rsquo;è nessuna chiamata da vincere. Sulla coda di resi e consegne dietro, c&rsquo;è un costo vero da togliere."],
  "rank_head": "Di cosa parlano le chiamate in entrata",
  "rank": ["Dov&rsquo;è il mio ordine / consegna in ritardo","Cambio taglia o reso","Stato del rimborso e quando arrivano i soldi","Torna disponibile: quando, e me lo tenete","Codice sconto e problemi di pagamento"],
  "questions_h2": "Cinque domande che un centralino moda sente ogni giorno - e cosa deve esserci nei tuoi sistemi",
  "questions_intro": "Nessuna di queste richiede competenza di prodotto. Tutte richiedono un record vivo e corretto. È tutto qui il lavoro in questa categoria: leggere il campo giusto, ad alta voce, alle undici di sera, nella lingua di chi chiama.",
  "questions": [
    ("&ldquo;Dov&rsquo;è il mio ordine, doveva arrivare martedì?&rdquo;","Eventi di tracking sull&rsquo;ordine, con il motivo dell&rsquo;eccezione detto in parole invece che come codice di stato.","carrier.events &middot; order.promised_date"),
    ("&ldquo;Posso cambiarlo con la taglia sopra?&rdquo;","Finestra di reso più disponibilità reale di quella taglia adesso - così la risposta è un cambio, non un rimborso.","returns.window &middot; variant.available"),
    ("&ldquo;L&rsquo;ho rispedito due settimane fa, il rimborso?&rdquo;","Scansione di rientro in magazzino e stato del rimborso sul gestore dei pagamenti.","rma.received_at &middot; payment.refund_state"),
    ("&ldquo;Quando torna disponibile?&rdquo;","Data dell&rsquo;ordine fornitore in arrivo per quella variante, e un richiamo fissato per il giorno in cui rientra.","po.expected_at &middot; variant.id"),
    ("&ldquo;Veste stretto? Di solito porto la 46.&rdquo;","Misure del capo per taglia dove le tieni, e passaggio esplicito a una persona dove non le tieni: è l&rsquo;unica domanda di questa categoria su cui l&rsquo;agente deve rifiutarsi di indovinare.","variant.measurements &middot; fallback: umano")],
  "workflows": [("Dov&rsquo;è il mio ordine","Il workflow di volume nella moda. Eventi corriere letti ad alta voce, eccezioni spiegate.","/it/casi-duso/dove-e-il-mio-ordine"),
                ("Gestione resi","Idoneità verificata contro la policy, cambio proposto prima del rimborso.","/it/casi-duso/gestione-resi"),
                ("Notifica ritorno in stock","Chiama chi lo voleva, invece di un&rsquo;email nello spam.","/it/casi-duso/notifica-ritorno-in-stock"),
                ("Feedback post-consegna","Intercetta il problema quando è ancora rimediabile, e si guadagna la recensione.","/it/casi-duso/feedback-post-consegna")],
  "transcript_meta": "In entrata &middot; 1 min 52 s &middot; lingua: italiano &middot; esito: cambio taglia, nessun rimborso",
  "transcript": [("caller","Buonasera, ho ordinato un cappotto la settimana scorsa, doveva arrivare martedì e il tracking è fermo da venerdì."),
    ("agent","Guardo subito. Ordine che finisce per 8213, il cappotto blu - è al deposito di Milano, è rimasto fermo sabato per un tentativo di consegna non riuscito all&rsquo;indirizzo. È previsto di nuovo in uscita domani mattina."),
    ("caller","Sabato non è passato nessuno."),
    ("agent","Succede più di quanto dovrebbe. Posso lasciarlo sul giro di domani, oppure dirottarlo a un punto di ritiro vicino a lei - ce n&rsquo;è uno a circa quattrocento metri dall&rsquo;indirizzo di consegna."),
    ("caller","Il punto di ritiro. E poi - se quando arriva la taglia è sbagliata, come funziona?"),
    ("agent","Trenta giorni dalla consegna. Se è la taglia e non il cappotto, farei un cambio invece di un reso: il blu è disponibile sia nella taglia sopra sia in quella sotto, quindi parte il giorno stesso in cui rientra il suo."),
    ("caller","Bene. Allora faccia il punto di ritiro."),
    ("agent","Dirottato, e le mando il codice di ritiro via SMS quando arriva. Le serve altro su quest&rsquo;ordine?")],
  "data_h2": "I dati dietro una risposta nella moda",
  "data_copy": "Questa categoria chiede meno ai dati di prodotto e più a quelli operativi. Il modo di sbagliare non è una raccomandazione errata: è una data di consegna sbagliata detta con sicurezza, che trasforma un cliente scocciato in due chiamate.",
  "data_rows": [("Eventi di tracking","Eventi grezzi, non un&rsquo;etichetta di stato, così un&rsquo;eccezione si spiega invece di recitarla."),
    ("Data promessa sull&rsquo;ordine","Quella detta davvero al checkout, che spesso non coincide con quella del corriere."),
    ("Finestra e policy di reso","Per canale e per promozione, così la risposta al telefono coincide con quella del portale."),
    ("Disponibilità variante","In tempo reale, per proporre un cambio invece di un rimborso mentre il cliente è in linea."),
    ("Ordini fornitore in arrivo","Date attese per variante, per richiami di riassortimento che valgono la pena.")],
  "proof": None,
  "faq": [("I clienti della moda chiamano davvero?","Prima di comprare quasi mai - è la risposta onesta, ed è il motivo per cui questa pagina parte dal post-acquisto. Chiamano quando un pacco è in ritardo, quando una taglia è sbagliata, o quando un rimborso non è arrivato. Nelle settimane di picco è quella la coda che straripa."),
    ("Ha senso se il nostro scontrino medio è basso?","Dipende dal volume di chiamate, non dallo scontrino. Se la coda post-acquisto è grande e stagionale il caso è deflection e retention. Se è piccola e regolare probabilmente basta il self-service, e nella call te lo diciamo."),
    ("Può gestire una domanda su taglia o vestibilità?","Solo dove tieni le misure del capo per taglia. Dove non le tieni passa la mano invece di indovinare: la vestibilità è l&rsquo;unica domanda di questa categoria in cui una risposta sbagliata detta con sicurezza si trasforma direttamente in un reso."),
    ("Cosa succede in una settimana di saldi con il volume triplicato?","La concorrenza è il punto. L&rsquo;agente prende tutte le chiamate insieme invece di metterle in coda, che è quando nella moda le chiamate perse esplodono - e chi rinuncia è chi ha un problema."),
    ("Funziona in più di una lingua?","Sì, e nella moda conta più che altrove, perché la quota cross-border è alta. L&rsquo;agente rileva la lingua alla prima battuta e ci resta, messaggio di follow-up compreso.")],
  "cta_h2": "Ascolta l&rsquo;agente su una chiamata di pacco in ritardo",
  "cta_sub": "Nella call lo facciamo girare sui tuoi dati d&rsquo;ordine - il tuo corriere, la tua policy resi, il tuo volume di picco.",
  "cta_hand": "venti minuti, senza slide"},

"salute-benessere": {
  "en": "health-wellness", "alias": ["Salute e Benessere", "Health &amp; Wellness"],
  "label": "Salute e Benessere", "when": "after", "scene": "health",
  "title": "Voice AI per E-Commerce Salute e Benessere | Abbonamenti | Sabato AI",
  "description": "Nel benessere le chiamate sono soprattutto abbonamenti, consegne e resi su prodotti aperti. Un agente vocale che le gestisce - e che non dà consigli sulla salute.",
  "h1": "Quasi tutte queste chiamate riguardano un abbonamento, non un prodotto.",
  "sub": "Salta il mese, cambia l&rsquo;indirizzo, dov&rsquo;è, posso rimandarlo indietro. L&rsquo;agente di Sabato gestisce la coda degli ordini ricorrenti su cui girano i brand del benessere - e passa a una persona qualunque cosa somigli a un consiglio sanitario.",
  "hand": "l&rsquo;agente non dà mai consigli sulla salute",
  "call_q": "&ldquo;Devo saltare la consegna del mese prossimo e cambiare indirizzo.&rdquo;",
  "call_meta": [("Intento rilevato","Modifica abbonamento"),("Dati letti","Abb. 7741 &middot; prossimo addebito"),("Esito","Saltato, indirizzo aggiornato")],
  "band_eyebrow": "Perché questa categoria telefona",
  "band_h2": "Un abbonamento è una relazione con una data di addebito, e la gente sulle date di addebito chiama.",
  "band_copy": ["I brand del benessere girano su ordini ricorrenti, e gli ordini ricorrenti generano una chiamata precisa, ad alto volume e bassa complessità: sospendilo, saltalo, spostalo, cambia la carta, cambia l&rsquo;indirizzo. Ognuna di queste è una scrittura a database che oggi qualcuno sta facendo a mano.",
                "La seconda coda sono i resi su prodotti aperti, dove la policy è più stretta che altrove e la risposta al telefono deve coincidere esattamente con quella del portale."],
  "rank_head": "Di cosa parlano le chiamate in entrata",
  "rank": ["Salta, sospendi o disdici l&rsquo;abbonamento","Dov&rsquo;è l&rsquo;ordine / consegna mancata","Posso rendere un prodotto aperto","Cambia data, indirizzo o carta","Ingredienti, allergeni e idoneità"],
  "questions_h2": "Cinque domande che un centralino del benessere sente ogni giorno - e cosa deve esserci nei tuoi sistemi",
  "questions_intro": "Quattro di queste sono ricerche su abbonamenti e logistica. La quinta è quella a cui l&rsquo;agente non deve rispondere da solo, e il confine fra le due è la cosa più importante di questa pagina.",
  "questions": [
    ("&ldquo;Posso saltare il mese prossimo?&rdquo;","Stato dell&rsquo;abbonamento e data del prossimo addebito, con il salto scritto durante la chiamata invece che promesso via email.","sub.next_charge_at &middot; sub.skip()"),
    ("&ldquo;Sono via - può arrivare una settimana dopo, a un altro indirizzo?&rdquo;","Data e indirizzo del prossimo ordine programmato, aggiornati prima dell&rsquo;orario limite.","sub.next_order.date &middot; sub.address"),
    ("&ldquo;L&rsquo;ho aperto e non mi trovo bene. Posso renderlo?&rdquo;","La tua policy di reso sugli alimentari e integratori aperti, più stretta di altre categorie e che deve coincidere con il portale.","returns.policy.opened_consumable"),
    ("&ldquo;Contiene lattosio?&rdquo;","La lista strutturata di allergeni e ingredienti sul prodotto, letta alla lettera - una lista, non un&rsquo;interpretazione.","attr.allergens[] &middot; attr.ingredients"),
    ("&ldquo;Posso prenderlo insieme alla mia terapia?&rdquo;","Niente. Qui si passa la mano. L&rsquo;agente non risponde a domande sulla salute, e lo dice chiaramente prima di trasferire.","escalate: umano &middot; no_advice_policy")],
  "workflows": [("Dov&rsquo;è il mio ordine","Consegne ricorrenti significano chiamate di stato ricorrenti. Il workflow di volume qui.","/it/casi-duso/dove-e-il-mio-ordine"),
                ("Gestione resi","Prodotti aperti, verificati contro una policy più stretta della media.","/it/casi-duso/gestione-resi"),
                ("Feedback post-consegna","Intercetta un problema su un ordine ricorrente prima che parta il successivo.","/it/casi-duso/feedback-post-consegna"),
                ("Notifica ritorno in stock","Clienti abituali che rivogliono quello che comprano sempre, il giorno in cui rientra.","/it/casi-duso/notifica-ritorno-in-stock")],
  "transcript_meta": "In entrata &middot; 1 min 31 s &middot; lingua: italiano &middot; esito: abbonamento saltato, indirizzo cambiato",
  "transcript": [("caller","Buongiorno, ho un ordine mensile e devo saltare il prossimo."),
    ("agent","Posso farlo io. Da questo numero risulta un abbonamento con addebito previsto il tre. Saltando quello, il successivo sarebbe il tre del mese dopo."),
    ("caller","Perfetto. E poi trasloco, quindi quello dopo dovrebbe andare altrove."),
    ("agent","Aggiorno l&rsquo;indirizzo adesso e vale da quell&rsquo;ordine in poi. Quando vuole."),
    ("caller","Via Ashfield 14, Bologna, 40126."),
    ("agent","Salvato. Quindi: niente il tre, poi l&rsquo;ordine abituale in via Ashfield il mese successivo."),
    ("caller","Un&rsquo;ultima cosa - prendo un anticoagulante, posso assumerlo insieme?"),
    ("agent","A questa non rispondo, e preferisco dirglielo invece di azzardare. Le passo il team adesso - e vale la pena chiederlo anche al suo farmacista.")],
  "data_h2": "I dati dietro una risposta nel benessere",
  "data_copy": "Il confine duro di questa categoria non è tecnico, è editoriale. L&rsquo;agente legge le liste ingredienti; non le interpreta. Tutto ciò che somiglia a una domanda sanitaria viene passato, e la regola è applicata nel workflow invece che lasciata al giudizio del modello.",
  "data_rows": [("Stato dell&rsquo;abbonamento","Data del prossimo addebito, salto e sospensione scrivibili in chiamata, non messi in coda per una persona."),
    ("Indirizzo e data di consegna","Sul prossimo ordine programmato, modificabili prima dell&rsquo;orario limite."),
    ("Policy di reso sull&rsquo;aperto","Più stretta che altrove, e deve coincidere esattamente con il portale."),
    ("Allergeni e ingredienti strutturati","Come lista da leggere alla lettera, mai riassunta o interpretata."),
    ("Regola di escalation","Qualunque domanda su salute, dosaggio o interazioni va a una persona. Applicata, non consigliata.")],
  "proof": None,
  "faq": [("L&rsquo;agente dà consigli sulla salute?","No. Liste di ingredienti e allergeni vengono lette alla lettera dai tuoi dati prodotto; qualunque cosa riguardi dosaggi, interazioni, patologie o idoneità viene passata a una persona, e l&rsquo;agente dice chiaramente che non risponderà. Il confine è applicato nel workflow, non lasciato al giudizio del modello."),
    ("Può modificare o disdire un abbonamento in chiamata?","Sì, dove la tua piattaforma consente scritture: saltare, sospendere, cambiare data, cambiare indirizzo. È la richiesta più frequente della categoria e quella oggi più spesso gestita a mano."),
    ("E i resi su prodotti aperti?","Verifica la tua policy reale, che qui è di solito più stretta che altrove. La parte importante è che la risposta al telefono e quella del portale siano la stessa."),
    ("È conforme per una categoria regolamentata?","Non siamo avvocati e non fingeremo di esserlo. Quello che possiamo dire è che l&rsquo;agente è vincolato a leggere i tuoi dati prodotto e non può generare claim sanitari, e che ogni chiamata è trascritta e verificabile. La posizione regolatoria resta tua."),
    ("Cosa serve per partire?","Accesso alla piattaforma abbonamenti, dati di ordini e prodotti con i campi allergeni strutturati, e la tua policy di reso sull&rsquo;aperto.")],
  "cta_h2": "Ascolta l&rsquo;agente su una chiamata di abbonamento",
  "cta_sub": "Nella call lo facciamo girare sui tuoi dati - compreso il punto in cui si rifiuta di rispondere.",
  "cta_hand": "compreso dove dice di no"},

"sport-fitness": {
  "en": "sports-fitness", "alias": ["Sport e Fitness", "Sports &amp; Fitness"],
  "label": "Sport e Fitness", "when": "after", "scene": "sports",
  "title": "Voice AI per E-Commerce Sport e Fitness | Taglie e Consegne | Sabato AI",
  "description": "Lo sport si divide in due: abbigliamento che chiama dopo l'acquisto, attrezzatura che chiama prima. Un agente vocale che gestisce entrambe le code.",
  "h1": "Due cataloghi, una linea telefonica.",
  "sub": "La canotta da running genera una chiamata di reso. Il vogatore genera una chiamata su misure e consegna prima ancora che qualcuno lo compri. L&rsquo;agente di Sabato gestisce entrambe, e le tratta per i lavori diversi che sono.",
  "hand": "l&rsquo;abbigliamento chiama dopo, l&rsquo;attrezzatura prima",
  "call_q": "&ldquo;Il vogatore passa da una porta normale, e chi lo porta di sopra?&rdquo;",
  "call_meta": [("Intento rilevato","Misure + consegna"),("Dati letti","Misure imballo &middot; tipo consegna"),("Esito","Consegna al piano fissata")],
  "band_eyebrow": "Perché questa categoria telefona",
  "band_h2": "Gran parte del catalogo non genera mai una chiamata. La fascia pesante non genera altro.",
  "band_copy": ["Lo sport è in realtà due business che condividono un numero. Abbigliamento e consumabili si comportano come la moda: le chiamate arrivano dopo il pacco, su cambi taglia e consegne in ritardo. L&rsquo;attrezzatura pesante si comporta come l&rsquo;arredamento: nessuno spende quattro cifre per un tapis roulant senza chiedere della porta e della consegna.",
                "Trattarle come una coda sola è il motivo per cui la linea sembra ingestibile. Servono risposte diverse da sistemi diversi, che è esattamente a cosa serve dividere i workflow."],
  "rank_head": "Di cosa parlano le chiamate in entrata",
  "rank": ["Dov&rsquo;è il mio ordine / consegna in ritardo","Cambio taglia su abbigliamento e calzature","Misure, peso e accessi per l&rsquo;attrezzatura","Montaggio, consegna al piano, ritiro del vecchio","Ricambi e garanzia sull&rsquo;attrezzatura"],
  "questions_h2": "Cinque domande che un centralino sport sente ogni giorno - e cosa deve esserci nei tuoi sistemi",
  "questions_intro": "Le prime due arrivano dalla metà abbigliamento del catalogo e le ultime tre dalla metà attrezzatura. Stessa linea, dati diversi dietro.",
  "questions": [
    ("&ldquo;Dov&rsquo;è il mio ordine?&rdquo;","Da quale metà del catalogo arriva decide la risposta: un evento di corriere, oppure uno slot di consegna con due operatori da riprenotare.","product.delivery_type &middot; carrier.events"),
    ("&ldquo;Queste scarpe calzano strette - posso cambiare taglia?&rdquo;","Calzata del modello oltre alla taglia, più disponibilità reale della versione larga: stretto è spesso un problema di calzata, non di numero.","variant.fitting_width &middot; returns.window"),
    ("&ldquo;Il vogatore passa da una porta normale?&rdquo;","Misure da imballo e peso, più se si ripiega - i tre dati che decidono un ordine di attrezzatura pesante.","product.packed_dims &middot; attr.folds"),
    ("&ldquo;Lo portate nella stanza o lo lasciate alla porta?&rdquo;","Livello di servizio di consegna di quel prodotto: al marciapiede, alla soglia, o al piano con montaggio.","product.delivery_type &middot; service.assembly"),
    ("&ldquo;La console del tapis roulant si è rotta - è coperta?&rdquo;","Durata di garanzia per componente e disponibilità ricambi per quell&rsquo;anno modello.","attr.warranty_by_part &middot; spares.by_model")],
  "workflows": [("Dov&rsquo;è il mio ordine","La metà abbigliamento del catalogo. Volume alto, complessità bassa.","/it/casi-duso/dove-e-il-mio-ordine"),
                ("Gestione resi","Cambi taglia su calzature e abbigliamento, proposti prima dei rimborsi.","/it/casi-duso/gestione-resi"),
                ("Consulenza pre-vendita","La metà attrezzatura. Misure, accessi e consegna su un ordine da quattro cifre.","/it/casi-duso/consulenza-pre-vendita"),
                ("Notifica ritorno in stock","Taglie e articoli di stagione, richiamati invece che mandati per email.","/it/casi-duso/notifica-ritorno-in-stock")],
  "transcript_meta": "In entrata &middot; 2 min 04 s &middot; lingua: italiano &middot; esito: consegna al piano fissata",
  "transcript": [("caller","Sto guardando il vogatore, ma va in una stanza al primo piano e vorrei sapere se ci arriva."),
    ("agent","Da imballato è 218 per 56 per 40 centimetri e pesa 44 chili, in un collo unico. Da una porta standard passa, ma 44 chili su una rampa di scale sono un lavoro da due persone."),
    ("caller","Era proprio quello che temevo."),
    ("agent","Allora prenda la consegna al piano invece di quella standard. Due operatori, lo portano nella stanza che indica e ritirano l&rsquo;imballo. Su questo articolo sono ventinove euro."),
    ("caller","E va montato?"),
    ("agent","Poco - la guida del sedile e la console, una ventina di minuti. Il montaggio nello stesso passaggio sono altri venti euro se preferisce non farlo."),
    ("caller","Faccia consegna e montaggio."),
    ("agent","Aggiunti entrambi. Il primo disponibile sul suo CAP è giovedì della prossima settimana, con finestra di due ore via SMS la sera prima.")],
  "data_h2": "I dati dietro una risposta nello sport",
  "data_copy": "La cosa da impostare bene è la divisione del catalogo. Se attrezzatura e abbigliamento vengono trattati come un tipo solo, l&rsquo;agente proporrà la consegna al marciapiede per un tapis roulant e due operatori per una t-shirt.",
  "data_rows": [("Eventi di tracking","Per la metà abbigliamento, dove il volume è più alto e la complessità più bassa."),
    ("Finestra di reso e taglie disponibili","Così un problema di taglia diventa un cambio invece di un rimborso."),
    ("Misure da imballo e peso","Per l&rsquo;attrezzatura. Una volta di mezzo le scale, il peso conta quanto l&rsquo;ingombro."),
    ("Livello di consegna per prodotto","Marciapiede, soglia o al piano - impostato sul prodotto, non dedotto."),
    ("Garanzia per componente e ricambi","L&rsquo;attrezzatura si rompe per pezzi, e la garanzia di solito cambia da pezzo a pezzo.")],
  "proof": None,
  "faq": [("Il nostro catalogo è quasi tutto abbigliamento - ha senso?","Allora il tuo caso è la coda post-acquisto: consegne, cambi, rimborsi. È lo stesso ragionamento della moda. Se quella coda è grande o esplode intorno ai saldi c&rsquo;è un costo da togliere; se è piccola e regolare te lo diciamo."),
    ("Regge bene la parte di attrezzatura pesante?","È a questo che servono i campi misure da imballo, peso e livello di consegna. Risponde alla domanda su porta e scale, poi prenota il tipo di consegna giusto - che è dove la maggior parte degli ordini di attrezzatura si blocca davvero."),
    ("Sa quando proporre un cambio invece di un rimborso?","Sì, dove la disponibilità è in tempo reale. Proporre la taglia adiacente mentre il cliente è al telefono è la mossa di retention più economica di questa categoria."),
    ("E nelle settimane di saldi o ai lanci?","Concorrenza. Ogni chiamata viene risposta subito invece che messa in coda, che è quando le chiamate perse esplodono - e chi rinuncia è chi ha un problema."),
    ("Cosa serve per partire?","Ordini e dati corriere, disponibilità varianti in tempo reale, e per l&rsquo;attrezzatura: misure da imballo, peso e livello di consegna per prodotto.")],
  "cta_h2": "Ascolta l&rsquo;agente su entrambi i tipi di chiamata",
  "cta_sub": "Porta alla call un ordine di abbigliamento e un codice di attrezzatura. Sono lavori diversi e si vede.",
  "cta_hand": "due cataloghi, una prova"},
}
